# -*- coding: UTF-8 -*-

#####################################################################
# List of spoken languages taken from Wikipedia:
#    http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
# and translated into a Python list of dictionaries.
#
# Copyless 2011 Juancarlo Añez <apalala@gmail.com>
#####################################################################

from __future__ import unicode_literals

spoken_languages = [
{ "language_name":"Abkhaz", "native_name":"аҧсуа бызшәа, аҧсшәа", "language_family":"Northwest Caucasian", "639-1":"ab", "639-2/t":"abk", "639-2/b":"abk", "639-3":"abk", "notes":"" } ,
{ "language_name":"Afar", "native_name":"Afaraf", "language_family":"Afro-Asiatic", "639-1":"aa", "639-2/t":"aar", "639-2/b":"aar", "639-3":"aar", "notes":"" } ,
{ "language_name":"Afrikaans", "native_name":"Afrikaans", "language_family":"Indo-European", "639-1":"af", "639-2/t":"afr", "639-2/b":"afr", "639-3":"afr", "notes":"" } ,
{ "language_name":"Akan", "native_name":"Akan", "language_family":"Niger–Congo", "639-1":"ak", "639-2/t":"aka", "639-2/b":"aka", "639-3":"aka + 2", "notes":"macrolanguage, Twi is [tw/twi], Fanti is [fat]" } ,
{ "language_name":"Albanian", "native_name":"gjuha shqipe", "language_family":"Indo-European", "639-1":"sq", "639-2/t":"sqi", "639-2/b":"alb", "639-3":"sqi + 4", "notes":"macrolanguage" } ,
{ "language_name":"Alemannic, Swiss German, Alsatian", "native_name":"Schwyzerdütsch, Elsassisch, Alemannisch", "language_family":"Indo-European", "639-1":" ", "639-2/t":"gsw", "639-2/b":"gsw", "639-3":"gsw", "notes":"" } ,
{ "language_name":"Amharic", "native_name":"አማርኛ", "language_family":"Afro-Asiatic", "639-1":"am", "639-2/t":"amh", "639-2/b":"amh", "639-3":"amh", "notes":"" } ,
{ "language_name":"Arabic", "native_name":"العربية", "language_family":"Afro-Asiatic", "639-1":"ar", "639-2/t":"ara", "639-2/b":"ara", "639-3":"ara +30", "notes":"macrolanguage, Standard Arabic is [arb]" } ,
{ "language_name":"Aragonese", "native_name":"aragonés", "language_family":"Indo-European", "639-1":"an", "639-2/t":"arg", "639-2/b":"arg", "639-3":"arg", "notes":"" } ,
{ "language_name":"Armenian", "native_name":"Հայերեն", "language_family":"Indo-European", "639-1":"hy", "639-2/t":"hye", "639-2/b":"arm", "639-3":"hye", "notes":"" } ,
{ "language_name":"Assamese", "native_name":"অসমীয়া", "language_family":"Indo-European", "639-1":"as", "639-2/t":"asm", "639-2/b":"asm", "639-3":"asm", "notes":"" } ,
{ "language_name":"Avaric", "native_name":"авар мацӀ, магӀарул мацӀ", "language_family":"Northeast Caucasian", "639-1":"av", "639-2/t":"ava", "639-2/b":"ava", "639-3":"ava", "notes":"" } ,
{ "language_name":"Avestan", "native_name":"avesta", "language_family":"Indo-European", "639-1":"ae", "639-2/t":"ave", "639-2/b":"ave", "639-3":"ave", "notes":"ancient" } ,
{ "language_name":"Aymara", "native_name":"aymar aru", "language_family":"Aymaran", "639-1":"ay", "639-2/t":"aym", "639-2/b":"aym", "639-3":"aym +2", "notes":"macrolanguage" } ,
{ "language_name":"Azerbaijani", "native_name":"azərbaycan dili", "language_family":"Turkic", "639-1":"az", "639-2/t":"aze", "639-2/b":"aze", "639-3":"aze + 2", "notes":"macrolanguage" } ,
{ "language_name":"Bambara", "native_name":"bamanankan", "language_family":"Niger–Congo", "639-1":"bm", "639-2/t":"bam", "639-2/b":"bam", "639-3":"bam", "notes":"" } ,
{ "language_name":"Bashkir", "native_name":"башҡорт теле", "language_family":"Turkic", "639-1":"ba", "639-2/t":"bak", "639-2/b":"bak", "639-3":"bak", "notes":"" } ,
{ "language_name":"Basque", "native_name":"euskara, euskera", "language_family":"Language isolate", "639-1":"eu", "639-2/t":"eus", "639-2/b":"baq", "639-3":"eus", "notes":"" } ,
{ "language_name":"Belarusian", "native_name":"беларуская мова", "language_family":"Indo-European", "639-1":"be", "639-2/t":"bel", "639-2/b":"bel", "639-3":"bel", "notes":"" } ,
{ "language_name":"Bengali", "native_name":"বাংলা", "language_family":"Indo-European", "639-1":"bn", "639-2/t":"ben", "639-2/b":"ben", "639-3":"ben", "notes":"" } ,
{ "language_name":"Bihari", "native_name":"भोजपुरी", "language_family":"Indo-European", "639-1":"bh", "639-2/t":"bih", "639-2/b":"bih", "639-3":"–", "notes":"Collective language code for Bhojpuri, Magahi, and Maithili" } ,
{ "language_name":"Bislama", "native_name":"Bislama", "language_family":"Creole", "639-1":"bi", "639-2/t":"bis", "639-2/b":"bis", "639-3":"bis", "notes":"" } ,
{ "language_name":"Bosnian", "native_name":"bosanski jezik", "language_family":"Indo-European", "639-1":"bs", "639-2/t":"bos", "639-2/b":"bos", "639-3":"bos", "notes":"" } ,
{ "language_name":"Breton", "native_name":"brezhoneg", "language_family":"Indo-European", "639-1":"br", "639-2/t":"bre", "639-2/b":"bre", "639-3":"bre", "notes":"" } ,
{ "language_name":"Bulgarian", "native_name":"български език", "language_family":"Indo-European", "639-1":"bg", "639-2/t":"bul", "639-2/b":"bul", "639-3":"bul", "notes":"" } ,
{ "language_name":"Burmese", "native_name":"ဗမာစာ", "language_family":"Sino-Tibetan", "639-1":"my", "639-2/t":"mya", "639-2/b":"bur", "639-3":"mya", "notes":"" } ,
{ "language_name":"Catalan; Valencian", "native_name":"català, valencià", "language_family":"Indo-European", "639-1":"ca", "639-2/t":"cat", "639-2/b":"cat", "639-3":"cat", "notes":"" } ,
{ "language_name":"Chamorro", "native_name":"Chamoru", "language_family":"Austronesian", "639-1":"ch", "639-2/t":"cha", "639-2/b":"cha", "639-3":"cha", "notes":"" } ,
{ "language_name":"Chechen", "native_name":"нохчийн мотт", "language_family":"Northeast Caucasian", "639-1":"ce", "639-2/t":"che", "639-2/b":"che", "639-3":"che", "notes":"" } ,
{ "language_name":"Chichewa; Chewa; Nyanja", "native_name":"chiCheŵa, chinyanja", "language_family":"Niger–Congo", "639-1":"ny", "639-2/t":"nya", "639-2/b":"nya", "639-3":"nya", "notes":"" } ,
{ "language_name":"Chinese", "native_name":"中文 (Zhōngwén), 汉语, 漢語", "language_family":"Sino-Tibetan", "639-1":"zh", "639-2/t":"zho", "639-2/b":"chi", "639-3":"zho +13", "notes":"macrolanguage" } ,
{ "language_name":"Chuvash", "native_name":"чӑваш чӗлхи", "language_family":"Turkic", "639-1":"cv", "639-2/t":"chv", "639-2/b":"chv", "639-3":"chv", "notes":"" } ,
{ "language_name":"Cornish", "native_name":"Kernewek", "language_family":"Indo-European", "639-1":"kw", "639-2/t":"cor", "639-2/b":"cor", "639-3":"cor", "notes":"" } ,
{ "language_name":"Corsican", "native_name":"corsu, lingua corsa", "language_family":"Indo-European", "639-1":"co", "639-2/t":"cos", "639-2/b":"cos", "639-3":"cos", "notes":"" } ,
{ "language_name":"Cree", "native_name":"ᓀᐦᐃᔭᐍᐏᐣ", "language_family":"Algonquian", "639-1":"cr", "639-2/t":"cre", "639-2/b":"cre", "639-3":"cre + 6", "notes":"macrolanguage" } ,
{ "language_name":"Croatian", "native_name":"hrvatski jezik", "language_family":"Indo-European", "639-1":"hr", "639-2/t":"hrv", "639-2/b":"hrv", "639-3":"hrv", "notes":"" } ,
{ "language_name":"Czech", "native_name":"čeština, český jazyk", "language_family":"Indo-European", "639-1":"cs", "639-2/t":"ces", "639-2/b":"cze", "639-3":"ces", "notes":"" } ,
{ "language_name":"Danish", "native_name":"dansk", "language_family":"Indo-European", "639-1":"da", "639-2/t":"dan", "639-2/b":"dan", "639-3":"dan", "notes":"" } ,
{ "language_name":"Divehi; Dhivehi; Maldivian;", "native_name":"ދިވެހި", "language_family":"Indo-European", "639-1":"dv", "639-2/t":"div", "639-2/b":"div", "639-3":"div", "notes":"" } ,
{ "language_name":"Dutch", "native_name":"Nederlands, Vlaams", "language_family":"Indo-European", "639-1":"nl", "639-2/t":"nld", "639-2/b":"dut", "639-3":"nld", "notes":"" } ,
{ "language_name":"Dzongkha", "native_name":"རྫོང་ཁ", "language_family":"Sino-Tibetan", "639-1":"dz", "639-2/t":"dzo", "639-2/b":"dzo", "639-3":"dzo", "notes":"" } ,
{ "language_name":"English", "native_name":"English", "language_family":"Indo-European", "639-1":"en", "639-2/t":"eng", "639-2/b":"eng", "639-3":"eng", "notes":"" } ,
{ "language_name":"Esperanto", "native_name":"Esperanto", "language_family":"Constructed", "639-1":"eo", "639-2/t":"epo", "639-2/b":"epo", "639-3":"epo", "notes":"constructed" } ,
{ "language_name":"Estonian", "native_name":"eesti, eesti keel", "language_family":"Uralic", "639-1":"et", "639-2/t":"est", "639-2/b":"est", "639-3":"est + 2", "notes":"macrolanguage" } ,
{ "language_name":"Ewe", "native_name":"Eʋegbe", "language_family":"Niger–Congo", "639-1":"ee", "639-2/t":"ewe", "639-2/b":"ewe", "639-3":"ewe", "notes":"" } ,
{ "language_name":"Faroese", "native_name":"føroyskt", "language_family":"Indo-European", "639-1":"fo", "639-2/t":"fao", "639-2/b":"fao", "639-3":"fao", "notes":"" } ,
{ "language_name":"Fijian", "native_name":"vosa Vakaviti", "language_family":"Austronesian", "639-1":"fj", "639-2/t":"fij", "639-2/b":"fij", "639-3":"fij", "notes":"" } ,
{ "language_name":"Finnish", "native_name":"suomi, suomen kieli", "language_family":"Uralic", "639-1":"fi", "639-2/t":"fin", "639-2/b":"fin", "639-3":"fin", "notes":"" } ,
{ "language_name":"French", "native_name":"français, langue française", "language_family":"Indo-European", "639-1":"fr", "639-2/t":"fra", "639-2/b":"fre", "639-3":"fra", "notes":"" } ,
{ "language_name":"Fula; Fulah; Pulaar; Pular", "native_name":"Fulfulde, Pulaar, Pular", "language_family":"Niger–Congo", "639-1":"ff", "639-2/t":"ful", "639-2/b":"ful", "639-3":"ful + 9", "notes":"macrolanguage" } ,
{ "language_name":"Galician", "native_name":"galego", "language_family":"Indo-European", "639-1":"gl", "639-2/t":"glg", "639-2/b":"glg", "639-3":"glg", "notes":"" } ,
{ "language_name":"Georgian", "native_name":"ქართული", "language_family":"South Caucasian", "639-1":"ka", "639-2/t":"kat", "639-2/b":"geo", "639-3":"kat", "notes":"" } ,
{ "language_name":"German", "native_name":"Deutsch", "language_family":"Indo-European", "639-1":"de", "639-2/t":"deu", "639-2/b":"ger", "639-3":"deu", "notes":"" } ,
{ "language_name":"Greek, Modern", "native_name":"ελληνικά", "language_family":"Indo-European", "639-1":"el", "639-2/t":"ell", "639-2/b":"gre", "639-3":"ell", "notes":"" } ,
{ "language_name":"Guaraní", "native_name":"Avañe'ẽ", "language_family":"Tupian", "639-1":"gn", "639-2/t":"grn", "639-2/b":"grn", "639-3":"grn + 5", "notes":"macrolanguage" } ,
{ "language_name":"Gujarati", "native_name":"ગુજરાતી", "language_family":"Indo-European", "639-1":"gu", "639-2/t":"guj", "639-2/b":"guj", "639-3":"guj", "notes":"" } ,
{ "language_name":"Haitian; Haitian Creole", "native_name":"Kreyòl ayisyen", "language_family":"Creole", "639-1":"ht", "639-2/t":"hat", "639-2/b":"hat", "639-3":"hat", "notes":"" } ,
{ "language_name":"Hausa", "native_name":"Hausa, هَوُسَ", "language_family":"Afro-Asiatic", "639-1":"ha", "639-2/t":"hau", "639-2/b":"hau", "639-3":"hau", "notes":"" } ,
{ "language_name":"Hebrew (modern)", "native_name":"עברית", "language_family":"Afro-Asiatic", "639-1":"he", "639-2/t":"heb", "639-2/b":"heb", "639-3":"heb", "notes":"" } ,
{ "language_name":"Herero", "native_name":"Otjiherero", "language_family":"Niger–Congo", "639-1":"hz", "639-2/t":"her", "639-2/b":"her", "639-3":"her", "notes":"" } ,
{ "language_name":"Hindi", "native_name":"हिन्दी, हिंदी", "language_family":"Indo-European", "639-1":"hi", "639-2/t":"hin", "639-2/b":"hin", "639-3":"hin", "notes":"" } ,
{ "language_name":"Hiri Motu", "native_name":"Hiri Motu", "language_family":"Austronesian", "639-1":"ho", "639-2/t":"hmo", "639-2/b":"hmo", "639-3":"hmo", "notes":"" } ,
{ "language_name":"Hungarian", "native_name":"Magyar", "language_family":"Uralic", "639-1":"hu", "639-2/t":"hun", "639-2/b":"hun", "639-3":"hun", "notes":"" } ,
{ "language_name":"Interlingua", "native_name":"Interlingua", "language_family":"Constructed", "639-1":"ia", "639-2/t":"ina", "639-2/b":"ina", "639-3":"ina", "notes":"constructed by International Auxiliary Language Association" } ,
{ "language_name":"Indonesian", "native_name":"Bahasa Indonesia", "language_family":"Austronesian", "639-1":"id", "639-2/t":"ind", "639-2/b":"ind", "639-3":"ind", "notes":"Covered by macrolanguage [ms/msa]" } ,
{ "language_name":"Interlingue", "native_name":"Originally called Occidental; then Interlingue after WWII", "language_family":"Constructed", "639-1":"ie", "639-2/t":"ile", "639-2/b":"ile", "639-3":"ile", "notes":"constructed by Edgar de Wahl, first published in 1922" } ,
{ "language_name":"Irish", "native_name":"Gaeilge", "language_family":"Indo-European", "639-1":"ga", "639-2/t":"gle", "639-2/b":"gle", "639-3":"gle", "notes":"" } ,
{ "language_name":"Igbo", "native_name":"Asụsụ Igbo", "language_family":"Niger–Congo", "639-1":"ig", "639-2/t":"ibo", "639-2/b":"ibo", "639-3":"ibo", "notes":"" } ,
{ "language_name":"Inupiaq", "native_name":"Iñupiaq, Iñupiatun", "language_family":"Eskimo–Aleut", "639-1":"ik", "639-2/t":"ipk", "639-2/b":"ipk", "639-3":"ipk + 2", "notes":"macrolanguage" } ,
{ "language_name":"Ido", "native_name":"Ido", "language_family":"Constructed", "639-1":"io", "639-2/t":"ido", "639-2/b":"ido", "639-3":"ido", "notes":"" } ,
{ "language_name":"Icelandic", "native_name":"Íslenska", "language_family":"Indo-European", "639-1":"is", "639-2/t":"isl", "639-2/b":"ice", "639-3":"isl", "notes":"" } ,
{ "language_name":"Italian", "native_name":"italiano", "language_family":"Indo-European", "639-1":"it", "639-2/t":"ita", "639-2/b":"ita", "639-3":"ita", "notes":"" } ,
{ "language_name":"Inuktitut", "native_name":"ᐃᓄᒃᑎᑐᑦ", "language_family":"Eskimo–Aleut", "639-1":"iu", "639-2/t":"iku", "639-2/b":"iku", "639-3":"iku + 2", "notes":"macrolanguage" } ,
{ "language_name":"Japanese", "native_name":"日本語 (にほんご)", "language_family":"Japonic", "639-1":"ja", "639-2/t":"jpn", "639-2/b":"jpn", "639-3":"jpn", "notes":"" } ,
{ "language_name":"Javanese", "native_name":"basa Jawa", "language_family":"Austronesian", "639-1":"jv", "639-2/t":"jav", "639-2/b":"jav", "639-3":"jav", "notes":"" } ,
{ "language_name":"Kalaallisut, Greenlandic", "native_name":"kalaallisut, kalaallit oqaasii", "language_family":"Eskimo–Aleut", "639-1":"kl", "639-2/t":"kal", "639-2/b":"kal", "639-3":"kal", "notes":"" } ,
{ "language_name":"Kannada", "native_name":"ಕನ್ನಡ", "language_family":"Dravidian", "639-1":"kn", "639-2/t":"kan", "639-2/b":"kan", "639-3":"kan", "notes":"" } ,
{ "language_name":"Kanuri", "native_name":"Kanuri", "language_family":"Nilo-Saharan", "639-1":"kr", "639-2/t":"kau", "639-2/b":"kau", "639-3":"kau + 3", "notes":"macrolanguage" } ,
{ "language_name":"Kashmiri", "native_name":"कश्मीरी, كشميري‎", "language_family":"Indo-European", "639-1":"ks", "639-2/t":"kas", "639-2/b":"kas", "639-3":"kas", "notes":"" } ,
{ "language_name":"Kazakh", "native_name":"қазақ тілі", "language_family":"Turkic", "639-1":"kk", "639-2/t":"kaz", "639-2/b":"kaz", "639-3":"kaz", "notes":"" } ,
{ "language_name":"Khmer", "native_name":"ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ", "language_family":"Austro-Asiatic", "639-1":"km", "639-2/t":"khm", "639-2/b":"khm", "639-3":"khm", "notes":"a.k.a. Cambodian" } ,
{ "language_name":"Kikuyu, Gikuyu", "native_name":"Gĩkũyũ", "language_family":"Niger–Congo", "639-1":"ki", "639-2/t":"kik", "639-2/b":"kik", "639-3":"kik", "notes":"" } ,
{ "language_name":"Kinyarwanda", "native_name":"Ikinyarwanda", "language_family":"Niger–Congo", "639-1":"rw", "639-2/t":"kin", "639-2/b":"kin", "639-3":"kin", "notes":"" } ,
{ "language_name":"Kirghiz, Kyrgyz", "native_name":"кыргыз тили", "language_family":"Turkic", "639-1":"ky", "639-2/t":"kir", "639-2/b":"kir", "639-3":"kir", "notes":"" } ,
{ "language_name":"Komi", "native_name":"коми кыв", "language_family":"Uralic", "639-1":"kv", "639-2/t":"kom", "639-2/b":"kom", "639-3":"kom +2", "notes":"macrolanguage" } ,
{ "language_name":"Kongo", "native_name":"KiKongo", "language_family":"Niger–Congo", "639-1":"kg", "639-2/t":"kon", "639-2/b":"kon", "639-3":"kon + 3", "notes":"macrolanguage" } ,
{ "language_name":"Korean", "native_name":"한국어 (韓國語), 조선어 (朝鮮語)", "language_family":"Language isolate", "639-1":"ko", "639-2/t":"kor", "639-2/b":"kor", "639-3":"kor", "notes":"" } ,
{ "language_name":"Kurdish", "native_name":"Kurdî, كوردی‎", "language_family":"Indo-European", "639-1":"ku", "639-2/t":"kur", "639-2/b":"kur", "639-3":"kur + 3", "notes":"macrolanguage" } ,
{ "language_name":"Kwanyama, Kuanyama", "native_name":"Kuanyama", "language_family":"Niger–Congo", "639-1":"kj", "639-2/t":"kua", "639-2/b":"kua", "639-3":"kua", "notes":"" } ,
{ "language_name":"Latin", "native_name":"latine, lingua latina", "language_family":"Indo-European", "639-1":"la", "639-2/t":"lat", "639-2/b":"lat", "639-3":"lat", "notes":"ancient" } ,
{ "language_name":"Luxembourgish, Letzeburgesch", "native_name":"Lëtzebuergesch", "language_family":"Indo-European", "639-1":"lb", "639-2/t":"ltz", "639-2/b":"ltz", "639-3":"ltz", "notes":"" } ,
{ "language_name":"Ganda", "native_name":"Luganda", "language_family":"Niger–Congo", "639-1":"lg", "639-2/t":"lug", "639-2/b":"lug", "639-3":"lug", "notes":"" } ,
{ "language_name":"Limburgish, Limburgan, Limburger", "native_name":"Limburgs", "language_family":"Indo-European", "639-1":"li", "639-2/t":"lim", "639-2/b":"lim", "639-3":"lim", "notes":"" } ,
{ "language_name":"Lingala", "native_name":"Lingála", "language_family":"Niger–Congo", "639-1":"ln", "639-2/t":"lin", "639-2/b":"lin", "639-3":"lin", "notes":"" } ,
{ "language_name":"Lao", "native_name":"ພາສາລາວ", "language_family":"Tai–Kadai", "639-1":"lo", "639-2/t":"lao", "639-2/b":"lao", "639-3":"lao", "notes":"" } ,
{ "language_name":"Lithuanian", "native_name":"lietuvių kalba", "language_family":"Indo-European", "639-1":"lt", "639-2/t":"lit", "639-2/b":"lit", "639-3":"lit", "notes":"" } ,
{ "language_name":"Luba-Katanga", "native_name":"Tshiluba", "language_family":"Niger–Congo", "639-1":"lu", "639-2/t":"lub", "639-2/b":"lub", "639-3":"lub", "notes":"" } ,
{ "language_name":"Latvian", "native_name":"latviešu valoda", "language_family":"Indo-European", "639-1":"lv", "639-2/t":"lav", "639-2/b":"lav", "639-3":"lav", "notes":"" } ,
{ "language_name":"Manx", "native_name":"Gaelg, Gailck", "language_family":"Indo-European", "639-1":"gv", "639-2/t":"glv", "639-2/b":"glv", "639-3":"glv", "notes":"" } ,
{ "language_name":"Macedonian", "native_name":"македонски јазик", "language_family":"Indo-European", "639-1":"mk", "639-2/t":"mkd", "639-2/b":"mac", "639-3":"mkd", "notes":"" } ,
{ "language_name":"Malagasy", "native_name":"Malagasy fiteny", "language_family":"Austronesian", "639-1":"mg", "639-2/t":"mlg", "639-2/b":"mlg", "639-3":"mlg +10", "notes":"macrolanguage" } ,
{ "language_name":"Malay", "native_name":"bahasa Melayu, بهاس ملايو‎", "language_family":"Austronesian", "639-1":"ms", "639-2/t":"msa", "639-2/b":"may", "639-3":"msa +13", "notes":"macrolanguage, Standard Malay is [zsm],Indonesian is [id/ind]" } ,
{ "language_name":"Malayalam", "native_name":"മലയാളം", "language_family":"Dravidian", "639-1":"ml", "639-2/t":"mal", "639-2/b":"mal", "639-3":"mal", "notes":"" } ,
{ "language_name":"Maltese", "native_name":"Malti", "language_family":"Afro-Asiatic", "639-1":"mt", "639-2/t":"mlt", "639-2/b":"mlt", "639-3":"mlt", "notes":"" } ,
{ "language_name":"Māori", "native_name":"te reo Māori", "language_family":"Austronesian", "639-1":"mi", "639-2/t":"mri", "639-2/b":"mao", "639-3":"mri", "notes":"" } ,
{ "language_name":"Marathi (Marāṭhī)", "native_name":"मराठी", "language_family":"Indo-European", "639-1":"mr", "639-2/t":"mar", "639-2/b":"mar", "639-3":"mar", "notes":"" } ,
{ "language_name":"Marshallese", "native_name":"Kajin M̧ajeļ", "language_family":"Austronesian", "639-1":"mh", "639-2/t":"mah", "639-2/b":"mah", "639-3":"mah", "notes":"" } ,
{ "language_name":"Mongolian", "native_name":"монгол", "language_family":"Mongolic", "639-1":"mn", "639-2/t":"mon", "639-2/b":"mon", "639-3":"mon +2", "notes":"macrolanguage" } ,
{ "language_name":"Nauru", "native_name":"Ekakairũ Naoero", "language_family":"Austronesian", "639-1":"na", "639-2/t":"nau", "639-2/b":"nau", "639-3":"nau", "notes":"" } ,
{ "language_name":"Navajo, Navaho", "native_name":"Diné bizaad, Dinékʼehǰí", "language_family":"Dené–Yeniseian", "639-1":"nv", "639-2/t":"nav", "639-2/b":"nav", "639-3":"nav", "notes":"" } ,
{ "language_name":"Norwegian Bokmål", "native_name":"Norsk bokmål", "language_family":"Indo-European", "639-1":"nb", "639-2/t":"nob", "639-2/b":"nob", "639-3":"nob", "notes":"Covered by macrolanguage [no/nor]" } ,
{ "language_name":"North Ndebele", "native_name":"isiNdebele", "language_family":"Niger–Congo", "639-1":"nd", "639-2/t":"nde", "639-2/b":"nde", "639-3":"nde", "notes":"" } ,
{ "language_name":"Nepali", "native_name":"नेपाली", "language_family":"Indo-European", "639-1":"ne", "639-2/t":"nep", "639-2/b":"nep", "639-3":"nep", "notes":"" } ,
{ "language_name":"Ndonga", "native_name":"Owambo", "language_family":"Niger–Congo", "639-1":"ng", "639-2/t":"ndo", "639-2/b":"ndo", "639-3":"ndo", "notes":"" } ,
{ "language_name":"Norwegian Nynorsk", "native_name":"Norsk nynorsk", "language_family":"Indo-European", "639-1":"nn", "639-2/t":"nno", "639-2/b":"nno", "639-3":"nno", "notes":"Covered by macrolanguage [no/nor]" } ,
{ "language_name":"Norwegian", "native_name":"Norsk", "language_family":"Indo-European", "639-1":"no", "639-2/t":"nor", "639-2/b":"nor", "639-3":"nor + 2", "notes":"macrolanguage, Bokmål is [nb/nob], Nynorsk is [nn/nno]" } ,
{ "language_name":"Nuosu", "native_name":"ꆈꌠ꒿ Nuosuhxop", "language_family":"Sino-Tibetan", "639-1":"ii", "639-2/t":"iii", "639-2/b":"iii", "639-3":"iii", "notes":"Standard form of Yi languages" } ,
{ "language_name":"South Ndebele", "native_name":"isiNdebele", "language_family":"Niger–Congo", "639-1":"nr", "639-2/t":"nbl", "639-2/b":"nbl", "639-3":"nbl", "notes":"" } ,
{ "language_name":"Occitan", "native_name":"occitan, lenga d'òc", "language_family":"Indo-European", "639-1":"oc", "639-2/t":"oci", "639-2/b":"oci", "639-3":"oci", "notes":"" } ,
{ "language_name":"Ojibwe, Ojibwa", "native_name":"ᐊᓂᔑᓈᐯᒧᐎᓐ", "language_family":"Algonquian", "639-1":"oj", "639-2/t":"oji", "639-2/b":"oji", "639-3":"oji + 7", "notes":"macrolanguage" } ,
{ "language_name":"Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic", "native_name":"ѩзыкъ словѣньскъ", "language_family":"Indo-European", "639-1":"cu", "639-2/t":"chu", "639-2/b":"chu", "639-3":"chu", "notes":"ancient" } ,
{ "language_name":"Oromo", "native_name":"Afaan Oromoo", "language_family":"Afro-Asiatic", "639-1":"om", "639-2/t":"orm", "639-2/b":"orm", "639-3":"orm +4", "notes":"macrolanguage" } ,
{ "language_name":"Oriya", "native_name":"ଓଡ଼ିଆ", "language_family":"Indo-European", "639-1":"or", "639-2/t":"ori", "639-2/b":"ori", "639-3":"ori", "notes":"" } ,
{ "language_name":"Ossetian, Ossetic", "native_name":"ирон æвзаг", "language_family":"Indo-European", "639-1":"os", "639-2/t":"oss", "639-2/b":"oss", "639-3":"oss", "notes":"" } ,
{ "language_name":"Panjabi, Punjabi", "native_name":"ਪੰਜਾਬੀ, پنجابی‎", "language_family":"Indo-European", "639-1":"pa", "639-2/t":"pan", "639-2/b":"pan", "639-3":"pan", "notes":"" } ,
{ "language_name":"Pāli", "native_name":"पाऴि", "language_family":"Indo-European", "639-1":"pi", "639-2/t":"pli", "639-2/b":"pli", "639-3":"pli", "notes":"ancient" } ,
{ "language_name":"Persian", "native_name":"فارسی", "language_family":"Indo-European", "639-1":"fa", "639-2/t":"fas", "639-2/b":"per", "639-3":"fas + 2", "notes":"macrolanguage" } ,
{ "language_name":"Polish", "native_name":"język polski, polszczyzna", "language_family":"Indo-European", "639-1":"pl", "639-2/t":"pol", "639-2/b":"pol", "639-3":"pol", "notes":"" } ,
{ "language_name":"Pashto, Pushto", "native_name":"پښتو", "language_family":"Indo-European", "639-1":"ps", "639-2/t":"pus", "639-2/b":"pus", "639-3":"pus + 3", "notes":"macrolanguage" } ,
{ "language_name":"Portuguese", "native_name":"português", "language_family":"Indo-European", "639-1":"pt", "639-2/t":"por", "639-2/b":"por", "639-3":"por", "notes":"" } ,
{ "language_name":"Quechua", "native_name":"Runa Simi, Kichwa", "language_family":"Quechuan", "639-1":"qu", "639-2/t":"que", "639-2/b":"que", "639-3":"que +44", "notes":"macrolanguage" } ,
{ "language_name":"Romansh", "native_name":"rumantsch grischun", "language_family":"Indo-European", "639-1":"rm", "639-2/t":"roh", "639-2/b":"roh", "639-3":"roh", "notes":"" } ,
{ "language_name":"Kirundi", "native_name":"Ikirundi", "language_family":"Niger–Congo", "639-1":"rn", "639-2/t":"run", "639-2/b":"run", "639-3":"run", "notes":"" } ,
{ "language_name":"Romanian, Moldavian, Moldovan", "native_name":"limba română, limba moldovenească", "language_family":"Indo-European", "639-1":"ro", "639-2/t":"ron", "639-2/b":"rum", "639-3":"ron", "notes":"[mo] for Moldavian has been withdrawn, recommending [ro] also for Moldavian" } ,
{ "language_name":"Russian", "native_name":"русский язык", "language_family":"Indo-European", "639-1":"ru", "639-2/t":"rus", "639-2/b":"rus", "639-3":"rus", "notes":"" } ,
{ "language_name":"Sanskrit (Saṁskṛta)", "native_name":"संस्कृतम्", "language_family":"Indo-European", "639-1":"sa", "639-2/t":"san", "639-2/b":"san", "639-3":"san", "notes":"ancient, still spoken" } ,
{ "language_name":"Sardinian", "native_name":"sardu", "language_family":"Indo-European", "639-1":"sc", "639-2/t":"srd", "639-2/b":"srd", "639-3":"srd + 4", "notes":"macrolanguage" } ,
{ "language_name":"Sindhi", "native_name":"सिन्धी, سنڌي، سندھی‎", "language_family":"Indo-European", "639-1":"sd", "639-2/t":"snd", "639-2/b":"snd", "639-3":"snd", "notes":"" } ,
{ "language_name":"Northern Sami", "native_name":"Davvisámegiella", "language_family":"Uralic", "639-1":"se", "639-2/t":"sme", "639-2/b":"sme", "639-3":"sme", "notes":"" } ,
{ "language_name":"Samoan", "native_name":"gagana fa'a Samoa", "language_family":"Austronesian", "639-1":"sm", "639-2/t":"smo", "639-2/b":"smo", "639-3":"smo", "notes":"" } ,
{ "language_name":"Sango", "native_name":"yângâ tî sängö", "language_family":"Creole", "639-1":"sg", "639-2/t":"sag", "639-2/b":"sag", "639-3":"sag", "notes":"" } ,
{ "language_name":"Serbian", "native_name":"српски језик", "language_family":"Indo-European", "639-1":"sr", "639-2/t":"srp", "639-2/b":"srp", "639-3":"srp", "notes":"" } ,
{ "language_name":"Scottish Gaelic; Gaelic", "native_name":"Gàidhlig", "language_family":"Indo-European", "639-1":"gd", "639-2/t":"gla", "639-2/b":"gla", "639-3":"gla", "notes":"" } ,
{ "language_name":"Shona", "native_name":"chiShona", "language_family":"Niger–Congo", "639-1":"sn", "639-2/t":"sna", "639-2/b":"sna", "639-3":"sna", "notes":"" } ,
{ "language_name":"Sinhala, Sinhalese", "native_name":"සිංහල", "language_family":"Indo-European", "639-1":"si", "639-2/t":"sin", "639-2/b":"sin", "639-3":"sin", "notes":"" } ,
{ "language_name":"Slovak", "native_name":"slovenčina, slovenský jazyk", "language_family":"Indo-European", "639-1":"sk", "639-2/t":"slk", "639-2/b":"slo", "639-3":"slk", "notes":"" } ,
{ "language_name":"Slovene", "native_name":"slovenski jezik, slovenščina", "language_family":"Indo-European", "639-1":"sl", "639-2/t":"slv", "639-2/b":"slv", "639-3":"slv", "notes":"" } ,
{ "language_name":"Somali", "native_name":"Soomaaliga, af Soomaali", "language_family":"Afro-Asiatic", "639-1":"so", "639-2/t":"som", "639-2/b":"som", "639-3":"som", "notes":"" } ,
{ "language_name":"Southern Sotho", "native_name":"Sesotho", "language_family":"Niger–Congo", "639-1":"st", "639-2/t":"sot", "639-2/b":"sot", "639-3":"sot", "notes":"" } ,
{ "language_name":"Spanish; Castilian", "native_name":"español, castellano", "language_family":"Indo-European", "639-1":"es", "639-2/t":"spa", "639-2/b":"spa", "639-3":"spa", "notes":"" } ,
{ "language_name":"Sundanese", "native_name":"Basa Sunda", "language_family":"Austronesian", "639-1":"su", "639-2/t":"sun", "639-2/b":"sun", "639-3":"sun", "notes":"" } ,
{ "language_name":"Swahili", "native_name":"Kiswahili", "language_family":"Niger–Congo", "639-1":"sw", "639-2/t":"swa", "639-2/b":"swa", "639-3":"swa +2", "notes":"macrolanguage" } ,
{ "language_name":"Swati", "native_name":"SiSwati", "language_family":"Niger–Congo", "639-1":"ss", "639-2/t":"ssw", "639-2/b":"ssw", "639-3":"ssw", "notes":"" } ,
{ "language_name":"Swedish", "native_name":"Svenska", "language_family":"Indo-European", "639-1":"sv", "639-2/t":"swe", "639-2/b":"swe", "639-3":"swe", "notes":"" } ,
{ "language_name":"Tamil", "native_name":"தமிழ்", "language_family":"Dravidian", "639-1":"ta", "639-2/t":"tam", "639-2/b":"tam", "639-3":"tam", "notes":"" } ,
{ "language_name":"Telugu", "native_name":"తెలుగు", "language_family":"Dravidian", "639-1":"te", "639-2/t":"tel", "639-2/b":"tel", "639-3":"tel", "notes":"" } ,
{ "language_name":"Tajik", "native_name":"тоҷикӣ, toğikī, تاجیکی‎", "language_family":"Indo-European", "639-1":"tg", "639-2/t":"tgk", "639-2/b":"tgk", "639-3":"tgk", "notes":"" } ,
{ "language_name":"Thai", "native_name":"ไทย", "language_family":"Tai–Kadai", "639-1":"th", "639-2/t":"tha", "639-2/b":"tha", "639-3":"tha", "notes":"" } ,
{ "language_name":"Tigrinya", "native_name":"ትግርኛ", "language_family":"Afro-Asiatic", "639-1":"ti", "639-2/t":"tir", "639-2/b":"tir", "639-3":"tir", "notes":"" } ,
{ "language_name":"Tibetan Standard, Tibetan, Central", "native_name":"བོད་ཡིག", "language_family":"Sino-Tibetan", "639-1":"bo", "639-2/t":"bod", "639-2/b":"tib", "639-3":"bod", "notes":"" } ,
{ "language_name":"Turkmen", "native_name":"Türkmen, Түркмен", "language_family":"Turkic", "639-1":"tk", "639-2/t":"tuk", "639-2/b":"tuk", "639-3":"tuk", "notes":"" } ,
{ "language_name":"Tagalog", "native_name":"Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔", "language_family":"Austronesian", "639-1":"tl", "639-2/t":"tgl", "639-2/b":"tgl", "639-3":"tgl", "notes":"Note: Filipino (Pilipino) has the code [fil]" } ,
{ "language_name":"Tswana", "native_name":"Setswana", "language_family":"Niger–Congo", "639-1":"tn", "639-2/t":"tsn", "639-2/b":"tsn", "639-3":"tsn", "notes":"" } ,
{ "language_name":"Tonga (Tonga Islands)", "native_name":"faka Tonga", "language_family":"Austronesian", "639-1":"to", "639-2/t":"ton", "639-2/b":"ton", "639-3":"ton", "notes":"" } ,
{ "language_name":"Turkish", "native_name":"Türkçe", "language_family":"Turkic", "639-1":"tr", "639-2/t":"tur", "639-2/b":"tur", "639-3":"tur", "notes":"" } ,
{ "language_name":"Tsonga", "native_name":"Xitsonga", "language_family":"Niger–Congo", "639-1":"ts", "639-2/t":"tso", "639-2/b":"tso", "639-3":"tso", "notes":"" } ,
{ "language_name":"Tatar", "native_name":"татар теле, tatar tele", "language_family":"Turkic", "639-1":"tt", "639-2/t":"tat", "639-2/b":"tat", "639-3":"tat", "notes":"" } ,
{ "language_name":"Twi", "native_name":"Twi", "language_family":"Niger–Congo", "639-1":"tw", "639-2/t":"twi", "639-2/b":"twi", "639-3":"twi", "notes":"Covered by macrolanguage [ak/aka]" } ,
{ "language_name":"Tahitian", "native_name":"Reo Tahiti", "language_family":"Austronesian", "639-1":"ty", "639-2/t":"tah", "639-2/b":"tah", "639-3":"tah", "notes":"One of the Reo Mā`ohi (languages of French Polynesia)" } ,
{ "language_name":"Uighur, Uyghur", "native_name":"Uyƣurqə, ئۇيغۇرچە‎", "language_family":"Turkic", "639-1":"ug", "639-2/t":"uig", "639-2/b":"uig", "639-3":"uig", "notes":"" } ,
{ "language_name":"Ukrainian", "native_name":"українська мова", "language_family":"Indo-European", "639-1":"uk", "639-2/t":"ukr", "639-2/b":"ukr", "639-3":"ukr", "notes":"" } ,
{ "language_name":"Urdu", "native_name":"اردو", "language_family":"Indo-European", "639-1":"ur", "639-2/t":"urd", "639-2/b":"urd", "639-3":"urd", "notes":"" } ,
{ "language_name":"Uzbek", "native_name":"O'zbek, Ўзбек, أۇزبېك‎", "language_family":"Turkic", "639-1":"uz", "639-2/t":"uzb", "639-2/b":"uzb", "639-3":"uzb + 2", "notes":"macrolanguage" } ,
{ "language_name":"Venda", "native_name":"Tshivenḓa", "language_family":"Niger–Congo", "639-1":"ve", "639-2/t":"ven", "639-2/b":"ven", "639-3":"ven", "notes":"" } ,
{ "language_name":"Vietnamese", "native_name":"Tiếng Việt", "language_family":"Austro-Asiatic", "639-1":"vi", "639-2/t":"vie", "639-2/b":"vie", "639-3":"vie", "notes":"" } ,
{ "language_name":"Volapük", "native_name":"Volapük", "language_family":"Constructed", "639-1":"vo", "639-2/t":"vol", "639-2/b":"vol", "639-3":"vol", "notes":"constructed" } ,
{ "language_name":"Walloon", "native_name":"walon", "language_family":"Indo-European", "639-1":"wa", "639-2/t":"wln", "639-2/b":"wln", "639-3":"wln", "notes":"" } ,
{ "language_name":"Welsh", "native_name":"Cymraeg", "language_family":"Indo-European", "639-1":"cy", "639-2/t":"cym", "639-2/b":"wel", "639-3":"cym", "notes":"" } ,
{ "language_name":"Wolof", "native_name":"Wollof", "language_family":"Niger–Congo", "639-1":"wo", "639-2/t":"wol", "639-2/b":"wol", "639-3":"wol", "notes":"" } ,
{ "language_name":"Western Frisian", "native_name":"Frysk", "language_family":"Indo-European", "639-1":"fy", "639-2/t":"fry", "639-2/b":"fry", "639-3":"fry", "notes":"" } ,
{ "language_name":"Xhosa", "native_name":"isiXhosa", "language_family":"Niger–Congo", "639-1":"xh", "639-2/t":"xho", "639-2/b":"xho", "639-3":"xho", "notes":"" } ,
{ "language_name":"Yiddish", "native_name":"ייִדיש", "language_family":"Indo-European", "639-1":"yi", "639-2/t":"yid", "639-2/b":"yid", "639-3":"yid + 2", "notes":"macrolanguage" } ,
{ "language_name":"Yoruba", "native_name":"Yorùbá", "language_family":"Niger–Congo", "639-1":"yo", "639-2/t":"yor", "639-2/b":"yor", "639-3":"yor", "notes":"" } ,
{ "language_name":"Zhuang, Chuang", "native_name":"Saɯ cueŋƅ, Saw cuengh", "language_family":"Tai–Kadai", "639-1":"za", "639-2/t":"zha", "639-2/b":"zha", "639-3":"zha +16", "notes":"macrolanguage" } ,
{ "language_name":"Zulu", "native_name":"isiZulu", "language_family":"Niger–Congo", "639-1":"zu", "639-2/t":"zul", "639-2/b":"zul", "639-3":"zul", "notes":"" }
]

def language_names():
    return list(sorted(l['language_name'] for l in spoken_languages))
