# -*- coding: utf-8 -*-
def get_airports():
    airports = sorted(AIRPORTS, key=lambda airport: airport[0]) #sortear por el país
    return [(a[2] , "%s - %s (%s)" % (a[0], a[1], a[2]) ) for a in airports]
    
AIRPORTS = [
( "Denmark", "Aalborg", "AAL" ),
( "Norway", "Aalesund", "AES" ),
( "Denmark - Bus service", "Aarhus", "ZID" ),
( "Denmark - Tirstrup", "Aarhus", "AAR" ),
( "Greenland", "Aasiaat", "JEG" ),
( "Iran", "Abadan", "ABD" ),
( "Russia", "Abakan", "ABA" ),
( "United Kingdom", "Aberdeen", "ABZ" ),
( "Saudi Arabia", "Abha", "AHB" ),
( "Cote d'Ivoire", "Abidjan", "ABJ" ),
( "United Arab Emirates", "Abu Dhabi", "AUH" ),
( "Egypt", "Abu Simbel", "ABS" ),
( "Nigeria", "Abuja", "ABV" ),
( "Mexico", "Acapulco", "ACA" ),
( "Venezuela", "Acarigua", "AGV" ),
( "Ghana", "Accra", "ACC" ),
( "Turkey", "Adana", "ADA" ),
( "Ethopia", "Addis Ababa", "ADD" ),
( "Australia", "Adelaide", "ADL" ),
( "Yemen", "Aden", "ADE" ),
( "Russia", "Adler/Sochi", "AER" ),
( "Algeria", "Adrar", "AZR" ),
( "Soloman Islands", "Afutara", "AFT" ),
( "Morocco", "Agadir", "AGA" ),
( "India", "Agartala", "IXA" ),
( "Papua New Guinea", "Agaun", "AUP" ),
( "France", "Agen", "AGF" ),
( "India", "Agra", "AGR" ),
( "Turkey", "Agri", "AJI" ),
( "Puerto Rico", "Aguadilla", "BQN" ),
( "Mexico", "Aguascalientes", "AGU" ),
( "Japan", "Aguni", "AGJ" ),
( "India", "Ahmedabad", "AMD" ),
( "Iran", "Ahwaz", "AWZ" ),
( "Marshall Islands", "Ailuk Island", "AIM" ),
( "Mauritania", "Aioun El Atrouss", "AEO" ),
( "Marshall Islands", "Airok", "AIC" ),
( "Cook Islands", "Aitutaki", "AIT" ),
( "India", "Aizawl", "AJL" ),
( "France", "Ajaccio", "AJA" ),
( "Japan", "Akita", "AXT" ),
( "China", "Aksu", "AKU" ),
( "Kazakhstan", "Aktyubinsk", "AKX" ),
( "Iceland", "Akureyri", "AEY" ),
( "United Arab Emirates", "Al Ain", "AAN" ),
( "Egypt", "Al Arish", "AAC" ),
( "Yemen", "Al Ghaydah", "AAY" ),
( "Morocco", "Al Hoceima", "AHU" ),
( "Saudi Arabia", "Al-Baha", "ABT" ),
( "Australia", "Albury", "ABX" ),
( "United Kingdom", "Alderney", "ACI" ),
( "Syrian Arab Republic", "Aleppo", "ALP" ),
( "South Africa", "Alexander Bay", "ALJ" ),
( "Egypt", "Alexandria", "ALY" ),
( "Greece", "Alexandroupolis", "AXD" ),
( "United Arab Emirates", "Al-Fujairah", "FJR" ),
( "Italy", "Alghero", "AHO" ),
( "Algeria", "Algiers", "ALG" ),
( "Spain", "Alicante", "ALC" ),
( "Australia", "Alice Springs", "ASP" ),
( "Kazakhstan", "Almaty", "AKX" ),
( "Spain", "Almeria", "LEI" ),
( "Indonesia", "Alor Island", "ARD" ),
( "Malaysia", "Alorsetar", "AOR" ),
( "Papua New Guinea", "Alotau", "GUR" ),
( "Norway", "Alta", "ALF" ),
( "Brazil", "Altamira", "ATM" ),
( "China", "Altay", "AAT" ),
( "Switzerland", "Altenrhein", "ACH" ),
( "Argentina", "Alto Rio Senguerr", "ARR" ),
( "Japan", "Amami O Shima", "ASJ" ),
( "Papua New Guinea", "Amazon Bay", "AZB" ),
( "Madagascar", "Ambanja", "IVA" ),
( "Madagascar", "Ambatomainty", "AMY" ),
( "Madagascar", "Ambatondrazaka", "WAM" ),
( "Indonesia", "Ambon", "AMQ" ),
( "Kenya", "Amboseli", "ASV" ),
( "Russia", "Amderma", "AMV" ),
( "Jordan - Queen Alia International", "Amman", "AMM" ),
( "Jordan - Civil/Marka Airport", "Amman", "ADJ" ),
( "India", "Amritsar", "ATQ" ),
( "Netherlands", "Amsterdam", "AMS" ),
( "Russia", "Anadyr", "DYR" ),
( "Madagascar", "Analalava", "HVA" ),
( "Russia", "Anapa", "AAQ" ),
( "Italy", "Ancona", "AOI" ),
( "Norway", "Andenes", "ANX" ),
( "Uzbekistan", "Andizhan", "AZN" ),
( "Vanuatu", "Aneityum", "AUY" ),
( "Sweden", "Angelholm/Helsingborg", "JHE" ),
( "France - Marce", "Angers", "ANE" ),
( "France - Rail service", "Angers", "QXG" ),
( "Indonesia", "Anggi", "AGD" ),
( "China", "Anging", "AQG" ),
( "France", "Angouleme", "ANG" ),
( "Anguilla", "Anguilla", "AXA" ),
( "Vanuatu", "Aniwa", "AWD" ),
( "China", "Ankang", "AKA" ),
( "Turkey - Esenboga", "Ankara", "ESB" ),
( "Turkey - Etimesqut", "Ankara", "ANK" ),
( "Madagascar", "Ankavandra", "JVA" ),
( "Algeria", "Annaba", "AAE" ),
( "France", "Annecy", "NCY" ),
( "Madagascar", "Antalaha", "ANM" ),
( "Turkey", "Antalya", "AYT" ),
( "Madgascar", "Antaninvarivo", "TNR" ),
( "Antigua and Barbuda", "Antigua", "ANU" ),
( "Chile", "Antofagasta", "ANF" ),
( "Madagascar", "Antsalova", "WAQ" ),
( "Madagascar", "Antsiranana", "DIE" ),
( "Madagascar", "Antsohihy", "WAI" ),
( "Belgium - Deurne Airport", "Antwerp", "ANR" ),
( "Belgium - Bus service", "Antwerp", "ZAY" ),
( "Japan", "Aomori", "AOJ" ),
( "Italy", "Aosta", "AOT" ),
( "Colombia", "Apartado", "APO" ),
( "Western Samoa", "Apia", "APW" ),
( "Western Samoa", "Apia", "FGI" ),
( "Jordan", "Aqaba", "AQJ" ),
( "Brazil", "Araca", "AJU" ),
( "Brazil", "Aracatuba", "ARU" ),
( "Romania", "Arad", "ARW" ),
( "Papua New Guinea", "Aragip", "ARP" ),
( "Brazil", "Araguaina", "AUX" ),
( "Brazil", "Arapoti", "AAG" ),
( "Saudi Arabia", "Arar", "RAE" ),
( "Colombia", "Arauca", "AUC" ),
( "Ethiopia", "Arba Mintch", "AMH" ),
( "Iran", "Ardabil", "ADU" ),
( "Peru", "Arequipa", "AQP" ),
( "Sweden", "Argelholm/Helsingborg", "AGH" ),
( "Australia", "Argyle", "GYL" ),
( "Chile", "Arica", "ARI" ),
( "Russia", "Arkangelsk", "ARH" ),
( "Colombia", "Armenia", "AXM" ),
( "Australia", "Armidale", "ARM" ),
( "Bahamas", "Arthur's Town", "ATC" ),
( "Uganda", "Arua", "RUA" ),
( "Aruba", "Aruba", "AUA" ),
( "Tanzania", "Arusha", "ARK" ),
( "Sweden", "Arvidsjaur", "AJR" ),
( "Japan", "Asahikawa", "AKJ" ),
( "Turkmenistan", "Ashgabat", "ASB" ),
( "Eritrea", "Asmara", "ASM" ),
( "Ethopia", "Asosa", "ASO" ),
( "Egypt", "Assiut", "ATZ" ),
( "Kazakhstan", "Astana", "TSE" ),
( "Russia", "Astrakhan", "ASF" ),
( "Spain and Canary Islands", "Asturias", "OVD" ),
( "Paraguay", "Asuncion", "ASU" ),
( "Egypt", "Aswan", "ASW" ),
( "Yemen", "Ataq", "AXK" ),
( "Greece", "Athens", "ATH" ),
( "Cook Islands", "Atiu Island", "AIU" ),
( "Solomon Islands", "Atoifi", "ATD" ),
( "French Polynesia", "Atuona", "AUQ" ),
( "Kazakhstan", "Atyrau", "GUW" ),
( "New Zealand", "Auckland", "AKL" ),
( "Germany", "Augsburg/Munich", "AGB" ),
( "Solomon Islands", "Auki", "AKS" ),
( "Marshall Islands", "Aur Island", "AUL" ),
( "India", "Aurangabad", "IXU" ),
( "France", "Aurillac", "AUR" ),
( "Australia", "Aurukun", "AUU" ),
( "France", "Avignon", "AVN" ),
( "Indonesia", "Ayawaki", "AYW" ),
( "Australia", "Ayers Rock", "AYQ" ),
( "Indonesia", "Babo", "BXB" ),
( "Philippines", "Bacolod", "BCD" ),
( "Spain", "Badajcz", "BJZ" ),
( "Indonesia", "Bade", "BXD" ),
( "Australia", "Badu Island", "BDD" ),
( "India", "Bagdogra", "IXB" ),
( "Ethiopia", "Baharpar", "BJR" ),
( "Pakistan", "Bahawalpur", "BHV" ),
( "Argentina", "Bahia Blanca", "BHI" ),
( "Panama", "Bahia Pinas", "BFQ" ),
( "Colombia", "Bahia Solano", "BSC" ),
( "Bahrain", "Bahrain", "BAH" ),
( "Romania", "Baia Mare", "BAY" ),
( "Papua New Guinea", "Baimuru", "VMU" ),
( "Azerbaijan", "Baku", "GYD" ),
( "Solomon Islands", "Balalae", "BAS" ),
( "Turkey", "Balikesir", "BZI" ),
( "Indonesia", "Balikpapan", "BPN" ),
( "Papua New Guinea", "Balimo", "OPU" ),
( "Australia", "Ballina", "BNK" ),
( "Chile", "Balmaceda", "BBA" ),
( "Iran", "Bam", "BXR" ),
( "Australia", "Bamaga", "ABM" ),
( "Mali", "Bamako", "BKO" ),
( "Indonesia", "Banda Aceh", "BTJ" ),
( "Iran", "Bandar Abbas", "BND" ),
( "Indonesia - Branti", "Bandar Lampung", "TKG" ),
( "Iran", "Bandar Lengeh", "BDH" ),
( "Brunei", "Bandar Seri Begawan", "BWN" ),
( "Indonesia", "Bandung", "BDO" ),
( "India", "Bangalore", "BLR" ),
( "China", "Bangda", "BPX" ),
( "Thailand", "Bangkok", "BKK" ),
( "Bosnia Herzegovina", "Banja Luka", "BNX" ),
( "Indonesia", "Banjarmasin", "BDJ" ),
( "Gambia", "Banjul", "BJL" ),
( "Viet Nam - Phung-Doc", "Banmethuot", "BMV" ),
( "Pakistan", "Bannu", "BNP" ),
( "Central African Republic", "Banqui", "BGF" ),
( "China", "Baoshan", "BSD" ),
( "China", "Baotou", "BAV" ),
( "Cuba", "Baracoa", "BCA" ),
( "Australia", "Barcaldine", "BCI" ),
( "Spain", "Barcelona", "BCN" ),
( "Venezuela", "Barcelona", "BLA" ),
( "Norway", "Bardufoss", "BDU" ),
( "Italy", "Bari", "BRI" ),
( "Venezuela", "Barinas", "BNS" ),
( "Malaysia", "Bario", "BBN" ),
( "Bangladesh", "Barisal", "BZL" ),
( "Russia", "Barnaul", "BAX" ),
( "Venezuela", "Barquisimeto", "BRM" ),
( "Costa Rica", "Barra Colorado", "BCL" ),
( "United Kingdom", "Barra", "BRR" ),
( "Colombia", "Barran Cabermeja", "EJA" ),
( "Colombia", "Barranquilla", "BAQ" ),
( "Brazil", "Barreiras", "BRA" ),
( "Philippines", "Basco", "BSO" ),
( "Switzerland", "Basel", "BSL" ),
( "Switzerland", "Basel/Mulhouse Railway Station", "ZDH" ),
( "Iran", "Bashehr", "BUZ" ),
( "France", "Bastia", "BIA" ),
( "Indonesia", "Batam", "BTH" ),
( "Australia", "Bathurst Island", "BRT" ),
( "Australia", "Bathurst", "BHS" ),
( "Turkey", "Batman", "BAL" ),
( "Algeria", "Batna", "BLJ" ),
( "Indonesia", "Batom", "BXM" ),
( "Norway", "Batsfijord", "BJF" ),
( "Cambodia", "Battambang", "BBM" ),
( "Georgia", "Batumi", "BUS" ),
( "Solomon Islands", "Batuna", "BPF" ),
( "Brazil", "Bauru", "BAU" ),
( "Cuba", "Bayamo", "BYM" ),
( "Germany", "Bayreuth", "BYU" ),
( "Algeria", "Bechar", "CBH" ),
( "Australia", "Bedourie", "BEU" ),
( "British Virgin Islands", "Beef Island", "EIS" ),
( "Ethiopia", "Beica", "BEI" ),
( "Libya - La Braq", "Beida", "LAQ" ),
( "China", "Beihai", "BHY" ),
( "China", "Beijing", "PEK" ),
( "Mozambique", "Beira", "BEW" ),
( "Lebanon", "Beirut", "BEY" ),
( "Algeria", "Bejaia", "BJA" ),
( "Mozambique", "Belaga", "BLG" ),
( "Brazil", "Belem", "BEL" ),
( "New Caledonia", "Belep Island", "BMY" ),
( "United Kingdom", "Belfast, Northern Ireland", "BFS" ),
( "United Kingdom", "Belfast", "BHD" ),
( "Russia", "Belgorod", "EGO" ),
( "Serbia and Montenegro - Beograd", "Belgrade", "BEG" ),
( "Belize - International", "Belize City", "BZE" ),
( "Belize - Municipal", "Belize City", "TZA" ),
( "Solomon Islands", "Bellona", "BNY" ),
( "Madagascar", "Belo", "BMD" ),
( "Brazil - Tancredo Neves Intl.", "Belo Horizonte", "CNF" ),
( "Brazil - Pampulha", "Belo Horizonte", "PLU" ),
( "United Kingdom", "Benbecula", "BEB" ),
( "Libya", "Benghazi", "BEN" ),
( "Indonesia", "Bengkulu", "BKS" ),
( "Indonesia", "Berau", "BEJ" ),
( "Somalia", "Berbera", "BBO" ),
( "Norway", "Bergen", "BGO" ),
( "France", "Bergerac", "EGC" ),
( "Norway", "Berlevag", "BVG" ),
( "Germany - All airports", "Berlin", "BER" ),
( "Germany - Tegel", "Berlin", "TXL" ),
( "Germany - Tempelhof", "Berlin", "THF" ),
( "Germany - Schoenefeld", "Berlin", "SXF" ),
( "Bermuda", "Bermuda", "BDA" ),
( "Switzerland - Belp Airport", "Berne", "BRN" ),
( "Switzerland - Rail service", "Berne", "ZDJ" ),
( "Madagascar", "Besalampy", "BPY" ),
( "France", "Beziers", "BZR" ),
( "Nepal", "Bhadrapur", "BDP" ),
( "Nepal", "Bhairawa", "BWA" ),
( "Myanmar", "Bhamo", "BMO" ),
( "Nepal", "Bharatpur", "BHR" ),
( "India", "Bhavnagar", "BHU" ),
( "India", "Bhopal", "BHO" ),
( "India", "Bhubaneswar", "BBI" ),
( "India", "Bhuj", "BHJ" ),
( "Indonesia", "Biak", "BIK" ),
( "France", "Biarritz", "BIQ" ),
( "Marshall Islands", "Bikini Atoll", "BII" ),
( "Spain", "Bilbao", "BIO" ),
( "Denmark", "Billund", "BLL" ),
( "Indonesia", "Bima", "BMU" ),
( "Bahamas", "Bimini", "BIM" ),
( "Bahamas", "Bimini", "NSB" ),
( "Malaysia", "Bintulu", "BTU" ),
( "Indonesia", "Bintuni", "NTI" ),
( "Nepal", "Biratragar", "BIR" ),
( "Australia", "Birdsville", "BVI" ),
( "United Kingdom", "Birmingham", "BHX" ),
( "Saudi Arabia", "Bisha", "BHH" ),
( "Kyrgyzstan", "Bishkek", "FRU" ),
( "Algeria", "Biskra", "BSK" ),
( "Guinea-Bissau", "Bissau", "OXB" ),
( "Australia", "Blackall", "BKQ" ),
( "United Kingdom", "Blackpool", "BLK" ),
( "Australia", "Blackwater", "BLT" ),
( "Russia", "Blagoveschensk", "BQS" ),
( "Malawi", "Blantyre", "BLZ" ),
( "New Zealand", "Blenheim", "BHE" ),
( "Brazil", "Blo Horizonte", "CNF" ),
( "South Africa", "Bloemfontein", "BFN" ),
( "Cape Verde", "Boa Vista", "BVC" ),
( "Papua New Guinea", "Boang", "BOV" ),
( "Brazil", "Boavista", "BVB" ),
( "Panama", "Bocas Del Toro", "BOC" ),
( "Norway", "Bodo", "BOO" ),
( "Turkey", "Bodrum", "BJV" ),
( "Colombia", "Bogota", "BOG" ),
( "Australia", "Boiju Island", "GIC" ),
( "Iran", "Bojnord", "BJB" ),
( "Indonesia", "Bokondini", "BUI" ),
( "Croatia", "Bol", "BWK" ),
( "Italy", "Bolzano", "BZO" ),
( "Congo", "Boma", "BOA" ),
( "India", "Bombay", "BOM" ),
( "Netherlands Antilles", "Bonaire", "BON" ),
( "Germany", "Bonn", "BNJ" ),
( "French Polynesia", "Bora Bora", "BOB" ),
( "France", "Bordeaux", "BOD" ),
( "Egypt", "Borg El Arab", "HBE" ),
( "Germany", "Borkum", "BMK" ),
( "Sweden", "Borlange", "BLE" ),
( "Denmark", "Bornholm", "RNN" ),
( "Australia", "Borroloola", "BOX" ),
( "Somalia", "Bossaro", "BSA" ),
( "Australia", "Boulia", "BQL" ),
( "Bulgaria", "Bourgas", "BOJ" ),
( "Australia", "Bourke", "BRK" ),
( "United Kingdom", "Bournemouth", "BOH" ),
( "Libya", "Brack", "BCQ" ),
( "Australia", "Brampton Island", "BMP" ),
( "Brazil", "Brasilia, DF", "BSB" ),
( "Slovakia", "Bratislava", "BTS" ),
( "Russia", "Bratsk", "BTK" ),
( "Denmark", "Braunschweig", "BWE" ),
( "Congo", "Brazzaville", "BZV" ),
( "Germany", "Bremen", "BRE" ),
( "France", "Brest", "BES" ),
( "Australia", "Brewarrina", "BWQ" ),
( "Barbados", "Bridgetown", "BGI" ),
( "Italy", "Brindisi", "BDS" ),
( "Australia", "Brisbane, Queensland", "BNE" ),
( "United Kingdom", "Bristol", "BRS" ),
( "France - Laroche", "Brive-La-Gaillarde", "BVE" ),
( "Czech Republic - Turany", "Brno", "BRQ" ),
( "Czech Republic - Bus service", "Brno", "ZDN" ),
( "Australia", "Broken Hill", "BHQ" ),
( "Norway", "Bronnoysund", "BNN" ),
( "Australia", "Broome", "BME" ),
( "Honduras", "Brus Laguna", "BHG" ),
( "Belgium - National", "Brussels", "BRU" ),
( "Belgium - Rail service", "Brussels", "ZYR" ),
( "Belguim - Charleroi", "Brussels", "CRL" ),
( "Colombia", "Bucaramanga", "BGA" ),
( "Romania - Baneasa", "Bucharest", "BBU" ),
( "Romania - Otopeni International", "Bucharest", "OTP" ),
( "Hungary", "Budapest", "BUD" ),
( "Argentina - Jorge Newbery", "Buenos Aires", "AEP" ),
( "Argentina - Ministro Pistarini", "Buenos Aires", "EZE" ),
( "Russia", "Bugulma", "UUA" ),
( "Burundi", "Bujumbura", "BJM" ),
( "Papua New Guinea", "Buka", "BUA" ),
( "Uzbekistan", "Bukhara", "BHK" ),
( "Malaysia", "Bukoba", "BKZ" ),
( "Zimbabwe", "Bulawayo", "BUQ" ),
( "Russia", "Bulgulma", "UUA" ),
( "Australia", "Bundaberg", "BDB" ),
( "Papua New Guinea", "Bunsil", "BXZ" ),
( "Somalia", "Burao", "BUO" ),
( "Fiji", "Bureta", "LEV" ),
( "Thailand", "Buri Ram", "BFV" ),
( "Australia", "Burketown", "BUC" ),
( "Australia", "Burnie", "BWT" ),
( "South Korea - Gimhae", "Busan", "PUS" ),
( "Philippines", "Butuan", "BXU" ),
( "Poland", "Bydgoszcz", "BZG" ),
( "Mexico", "Cabo San Lucas, 'Los Cabos'", "SJD" ),
( "France", "Caen", "CFR" ),
( "Philippines - Lumbia", "Cagayan De Oro", "CGY" ),
( "Italy", "Cagliari", "CAG" ),
( "Australia", "Cairns", "CNS" ),
( "Egypt", "Cairo", "CAI" ),
( "Peru", "Cajamarca", "CJA" ),
( "Nigeria", "Calabar", "CBQ" ),
( "Chile", "Calama", "CJC" ),
( "India", "Calcutta", "CCU" ),
( "Colombia", "Cali", "CLO" ),
( "France", "Calvi", "CLY" ),
( "Cuba", "Camaguey", "CMW" ),
( "United Kingdom", "Cambridge", "CBG" ),
( "Argentina", "Camodoro", "CRD" ),
( "United Kingdom", "Campbeltown", "CAL" ),
( "Mexico", "Campeche", "CPE" ),
( "Brazil", "Campina Grande", "CPV" ),
( "Brazil", "Campinas", "CPQ" ),
( "Brazil", "Campo Grande", "CGR" ),
( "Brazil", "Campos", "CAW" ),
( "Venezuela", "Canaima", "CAS" ),
( "Australia", "Canberra", "CBR" ),
( "Mexico", "Cancun", "CUN" ),
( "France - Mandelieu", "Cannes", "CEQ" ),
( "France - Coisette Heliport", "Cannes", "JCA" ),
( "France - Vieux Port", "Cannes", "QYW" ),
( "Saint Vincent and the Grenadines", "Canouan", "CIW" ),
( "Haiti", "Cap Haitien", "CAP" ),
( "Papua New Guinea", "Cape Orford", "CPI" ),
( "South Africa", "Cape Town", "CPT" ),
( "Papua New Guinea", "Cape Vogel", "CVL" ),
( "Venezuela", "Caracas", "CCS" ),
( "Brazil", "Carajas", "CKS" ),
( "France", "Carcassonne", "CCF" ),
( "United Kingdom", "Cardiff", "CWL" ),
( "Australia", "Carnarvon", "CVQ" ),
( "Costa Rica", "Carrillo", "RIK" ),
( "Colombia", "Cartagena", "CTG" ),
( "Venezuela", "Carupani", "CUP" ),
( "Morocco - Anfa", "Casablanca", "CAS" ),
( "Morocco - Mohamed V", "Casablanca", "CMN" ),
( "Brazil", "Cascavel", "CAC" ),
( "Australia", "Casino", "CSI" ),
( "Fiji", "Castaway", "CST" ),
( "France", "Castres", "DCM" ),
( "Argentina", "Catamarca", "CTC" ),
( "Italy", "Catania", "CTA" ),
( "Colombia", "Caucasia", "CAQ" ),
( "Brazil", "Caxias Do Sul", "CXJ" ),
( "French Guiana", "Cayenne", "CAY" ),
( "Cambodia", "Cayman Brac Is", "CYB" ),
( "Cuba", "Cayo Largo Del Sur", "CYO" ),
( "Philippines - Matan International", "Cebu", "CEB" ),
( "Australia", "Cedun", "CED" ),
( "Spain and Canary Islands", "Ceuta", "JCU" ),
( "Iran", "Chah-Bahar", "ZBR" ),
( "France", "Chambery", "CMF" ),
( "India", "Chandigarh", "IXC" ),
( "China", "Changchun", "CGQ" ),
( "China", "Changde", "CGD" ),
( "Panama", "Changuinda", "CHX" ),
( "China", "Changzhou", "CZX" ),
( "Greece", "Chania", "CHQ" ),
( "China", "Chaoyang", "CHG" ),
( "Brazil", "Chapeco", "XAP" ),
( "Australia", "Charleville", "CTL" ),
( "New Zealand", "Chatham Island", "CHT" ),
( "Russia", "Cheboksary", "CSY" ),
( "Russia", "Chelybinsk", "CEK" ),
( "India", "Chennai", "MAA" ),
( "South Korea", "Cheongju", "CJJ" ),
( "Russia", "Cherepovets", "CEE" ),
( "China", "Chergdu", "CTU" ),
( "United Kingdom", "Chester", "CEG" ),
( "Mexico", "Chetumal", "CTM" ),
( "Russia", "Chevepovets", "CEE" ),
( "Taiwan", "Chi Mei", "CMJ" ),
( "Thailand", "Chiang Mai", "CNX" ),
( "Thailand", "Chiang Rai", "CEI" ),
( "Taiwan", "Chiayi", "CYI" ),
( "Peru", "Chicayo", "CIX" ),
( "China", "Chifeng", "CIF" ),
( "Mexico", "Chihuahua", "CUU" ),
( "Chile", "Chillan", "YAI" ),
( "Zambia", "Chipata", "CIP" ),
( "Republic of Moldova", "Chisinau", "KIV" ),
( "Russia", "Chita", "HTA" ),
( "Pakistan", "Chitral", "CJL" ),
( "Panama", "Chitre", "CTD" ),
( "Bangladesh", "Chittagong", "CGP" ),
( "Solomon Islands", "Choiseul Bay", "CHY" ),
( "China", "Chongqing", "CKG" ),
( "New Zealand", "Christchurch", "CHC" ),
( "Christmas Island", "Christmas Island", "XCH" ),
( "Fiji", "Cicia", "ICI" ),
( "Cuba", "Ciego De Avila", "AVI" ),
( "Venezuela", "Ciudad Bolivar", "CBL" ),
( "Mexico", "Ciudad Del Carmen", "CME" ),
( "Paraguay", "Ciudad del Este", "AGT" ),
( "Mexico", "Ciudad Juarez", "CJS" ),
( "Mexico", "Ciudad Obregon", "CEN" ),
( "Mexico", "Ciudad Victoria", "CVM" ),
( "France", "Clermont-ferrand", "CFE" ),
( "Australia", "Cleve", "CVC" ),
( "Australia", "Cloncurry", "CNJ" ),
( "Malawi", "Club Makokola", "CMK" ),
( "Romania", "Cluj", "CLJ" ),
( "Australia", "Cobar", "CAZ" ),
( "Bolivia", "Cobija", "CIJ" ),
( "Bolivia", "Cochabamba", "CBB" ),
( "India", "Cochin", "COK" ),
( "Australia", "Coconut Island", "CNC" ),
( "Cocos (Keeling) Islands", "Cocos Islands", "CCK" ),
( "Australia", "Coen", "CUQ" ),
( "Australia", "Coffs Harbor", "CFS" ),
( "India", "Coimbatore", "CJB" ),
( "Mexico", "Colima", "CLQ" ),
( "Germany - Rail service", "Cologne", "QKL" ),
( "Germany - Cologne/Bonn", "Cologne", "CGN" ),
( "Sri Lanka", "Colombo", "CMB" ),
( "Panama", "Colon", "ONX" ),
( "Guinea", "Conakry", "CKY" ),
( "Chile", "Concepcion", "CCP" ),
( "Argentina", "Concordia", "COC" ),
( "Colombia", "Condoto", "COG" ),
( "Romania", "Constanta", "CND" ),
( "Algeria", "Constantine", "CZL" ),
( "Panama", "Contadora", "OTD" ),
( "Australia", "Coober Pedy", "CPD" ),
( "Australia", "Cooktown", "CTN" ),
( "Australia", "Cooma, NS", "OOM" ),
( "Australia", "Coonamble", "CNB" ),
( "Denmark", "Copenhagen", "CPH" ),
( "Chile", "Copiapo", "CPO" ),
( "Argentina", "Cordoba", "COR" ),
( "Ireland", "Cork", "ORK" ),
( "Venezuela", "Coro", "CZE" ),
( "Belize", "Corozal", "CZH" ),
( "Argentina", "Corrientes", "CNQ" ),
( "Brazil", "Corumba", "CMG" ),
( "Portugal", "Corvo Island", "CVU" ),
( "Philippines", "Cotabato", "CBO" ),
( "Benin", "Cotarou", "COC" ),
( "Bangladesh", "Cox's Bazar", "CXB" ),
( "Mexico", "Cozumel", "CZM" ),
( "Vanuatu", "Craig Cove", "CCV" ),
( "Brazil", "Criciuma", "CCM" ),
( "Australia", "Croker Island", "CKI" ),
( "Bahamas", "Crooked Island", "CRI" ),
( "Italy", "Crotone", "CRV" ),
( "Brazil", "Cruzeiro Do Sul", "CZS" ),
( "Colombia", "Cucata", "CUC" ),
( "Ecuador", "Cuenca", "CUE" ),
( "Mexico", "Cuernavaca", "CVJ" ),
( "Brazil", "Cuiaba", "CGB" ),
( "Mexico", "Culiacan", "CUL" ),
( "Venezuela", "Cumana", "CUM" ),
( "Australia", "Cunnamulla", "CMA" ),
( "Netherlands Antilles", "Curacao", "CUR" ),
( "Brazil", "Curitiba", "CWB" ),
( "Peru", "Cuzco", "CUZ" ),
( "Viet Nam", "Da Nang", "DAD" ),
( "Indonesia", "Dabra", "DRH" ),
( "South Korea", "Daegu", "TAE" ),
( "Senegal", "Dakar", "DKR" ),
( "Morocco", "Dakhla", "VIL" ),
( "Turkey", "Dalaman", "DLM" ),
( "VietNam", "Dalat Lienkhang", "DLI"),
( "China", "Dali City", "DLU" ),
( "China", "Dalian", "DLC" ),
( "Syrian Arab Republic", "Damascus", "DAM" ),
( "Saudi Arabia", "Dammam", "DMM" ),
( "Belize", "Dangriga", "DGA" ),
( "Tanzania", "Dar Es Salaam", "DAR" ),
( "Australia", "Darnley Island, QL", "NLF" ),
( "Papua New Guinea", "Daru", "DAU" ),
( "Australia", "Darwin, Northern Territory", "DRW" ),
( "Indonesia", "Datadawai", "DTD" ),
( "Philipines - Mati", "Davao", "DVO" ),
( "Panama", "David", "DAV" ),
( "Myanmar", "Dawe", "TVY" ),
( "China", "Daxian", "DAX" ),
( "China", "Dayang", "DYG" ),
( "Australia", "Daydream Is", "DDI" ),
( "France", "Deauville", "DOL" ),
( "Ethiopia", "Debra Marcos", "DBM" ),
( "Ethiopia", "Debra Tabor", "DBT" ),
( "Syria - Al Jafrah", "Deirezzor", "DEZ" ),
( "India", "Delhi", "DEL" ),
( "Ethiopia", "Dembidollo", "DEM" ),
( "Australia", "Denham", "DNM" ),
( "Turkey", "Denizli", "DNZ" ),
( "Indonesia", "Denpasar Bali", "DPS" ),
( "Pakistan", "Dera Ghazi", "DEA" ),
( "Pakistan", "Dera Ismail Khan", "DSK" ),
( "Australia", "Derby", "DRB" ),
( "Papua New Guinea", "Derim", "DER" ),
( "Ethiopia", "Dessie", "DSE" ),
( "Australia", "Devonport", "DPO" ),
( "Bangledesh - Zia International", "Dhaka", "DAC" ),
( "India", "Dibrugarn", "DIB" ),
( "Viet Nam - Gialam", "Dien Bien Phu", "DIN" ),
( "France", "Dijon", "DIJ" ),
( "Indonesia", "Dili", "DIL" ),
( "Vanuata", "Dillons Bay", "DLY" ),
( "India", "Dimapur", "DMU" ),
( "France", "Dinard", "DNR" ),
( "Philippines", "Dipolog", "DPL" ),
( "Ethiopia", "Dire Dawa", "DIR" ),
( "India", "Div", "DIU" ),
( "Turkey", "Diyarbakir", "DIY" ),
( "Algeria", "Djanet", "DJG" ),
( "Tunisia", "Djerba", "DJE" ),
( "Djibouti", "Djibouti", "JIB" ),
( "Ukraine", "Dnepropetrovsk", "DNK" ),
( "Indonesia", "Dobo", "DOB" ),
( "Tanzania", "Dodoma", "DOD" ),
( "Papua New Guinea", "Dodoima", "DDM" ),
( "Qatar", "Doha", "DOH" ),
( "Dominica - Cane Field", "Dominica", "DCF" ),
( "Dominica - Melville Hall", "Dominica", "DOM" ),
( "Ireland", "Donegal", "CFN" ),
( "Ukraine", "Donetsk", "DOK" ),
( "Sudan", "Dongola", "DOG" ),
( "Australia", "Doomadgee", "DMD" ),
( "Germany", "Dortmund", "DTM" ),
( "Brazil", "Dourados", "DOU" ),
( "Cameroon", "Dovala", "DLA" ),
( "Germany", "Dresden", "DRS" ),
( "United Arab Emirates - Bus Station", "Dubai", "XNB" ),
( "United Arab Emirates - International", "Dubai", "DXB" ),
( "Australia", "Dubbo", "DBO" ),
( "Ireland", "Dublin", "DUB" ),
( "Croatia", "Dubrovnik", "DBV" ),
( "Philippines", "Dumaguete", "DGT" ),
( "Indonesia", "Dumai", "DUM" ),
( "United Kingdom", "Dundee", "DND" ),
( "New Zealand", "Dunedin", "DUD" ),
( "China", "Dunhuang", "DNH" ),
( "Australia", "Dunk Island", "DKI" ),
( "Mexico", "Durango", "DGO" ),
( "South Africa", "Durban", "DUR" ),
( "Tajikistan", "Dushanbe", "DYU" ),
( "Germany - International", "Dusseldorf", "DUS" ),
( "Germany - Moenchen-Gl.", "Dusseldorf", "MGL" ),
( "Germany - Rail service", "Dusseldorf", "QDU" ),
( "Mayotte", "Dzaoudzi", "DZA" ),
( "South Africa", "East London", "ELS" ),
( "Marshall Islands", "Ebon", "EBO" ),
( "United Kingdom", "Eday", "EOI" ),
( "United Kingdom", "Edinburgh", "EDI" ),
( "Turkey", "Edremit", "EDO" ),
( "Australia", "Edward River", "EDR" ),
( "Iceland", "Egilsstadir", "EGS" ),
( "Netherlands", "Eindhoven", "EIN" ),
( "Germany", "Eisenach", "EIB" ),
( "Russia", "Ekaterinburg", "SVX" ),
( "Argentina", "El Bolsan", "EHL" ),
( "Sudan", "El Fasher", "ELF" ),
( "Argentina", "El Maiten", "EMX" ),
( "Sudan", "El Obeid", "EBD" ),
( "Algeria", "El Oved", "ELU" ),
( "Dominician Republic - El Portillo", "El Portillo/Samana", "EPS" ),
( "Panama", "El Real", "ELE" ),
( "Chile", "El Salvador", "ESR" ),
( "Venezuela", "El Vigia", "VIG" ),
( "Colombia", "El Yopal", "EYP" ),
( "Italy", "Elat", "ETH" ),
( "Turkey", "Elazig", "EZS" ),
( "Italy", "Elba Island", "EBA" ),
( "Australia", "Elcho Island", "ELC" ),
( "Kenya", "Eldoret", "EDL" ),
( "Bahamas", "Eleuthera Island", "ELH" ),
( "Russia", "Elista", "ESL" ),
( "Vanuata", "Emae", "EAE" ),
( "Papua New Guinea", "Embessa", "EMS" ),
( "Australia", "Emerald", "EMD" ),
( "Papua New Guinea", "Emo", "EMO" ),
( "Indonesia", "Enarotali", "EWI" ),
( "Indonesia", "Ende", "ENE" ),
( "Marshall Islands", "Enewetak Island", "ENT" ),
( "Finland", "Enontekio", "ENF" ),
( "China", "Enshi", "ENH" ),
( "Uganda", "Entebbe", "EBB" ),
( "Nigeria", "Enugu", "ENU" ),
( "France", "Epinal", "EPL" ),
( "Cyprus", "Ercan", "ECN" ),
( "Germany", "Erfurt", "ERF" ),
( "Turkey", "Erzincan", "ERC" ),
( "Turkey", "Erzurum", "ERZ" ),
( "Denmark - Esbjerg Airport", "Esbjerg", "EBJ" ),
( "Denmark - Rail service", "Esbjerg", "ZBB" ),
( "Ecuador", "Esmeraldas", "ESM" ),
( "Australia", "Esperance", "EPR" ),
( "Vanuatu", "Espiritu Santo", "SON" ),
( "Argentina", "Esquel", "EQS" ),
( "United Kingdom", "Eveter", "EXT" ),
( "Indonesia", "Ewer", "EWE" ),
( "Australia", "Exmouth Gulf", "EXM" ),
( "Norway", "Fagernes", "VDB" ),
( "United Kingdom", "Fair Isle", "FIE" ),
( "Pakistan", "Faisalabad", "LYP" ),
( "Puerto Rico", "Fajard", "FAJ" ),
( "Indonesia", "Fak Fak", "FKQ" ),
( "French Polynesia", "Fakarava", "FAV" ),
( "Madagascar", "Farafangana", "RVA" ),
( "Portugal", "Faro", "FAO" ),
( "Faroe Islands", "Faroe Islands", "FAE" ),
( "Solomon Islands", "Fera Island", "FRE" ),
( "Uzbekistan", "Fergana", "FEG" ),
( "Brazil", "Fernando De Noronha", "FEN" ),
( "Morocco", "Fez", "FEZ" ),
( "Madagascar", "Fianarantsoa", "WFI" ),
( "France", "Figari", "FSC" ),
( "United Kingdom", "Filton", "FZO" ),
( "Germany", "Finkenwerder", "XFW" ),
( "Australia", "Fitzroy Crossing", "FIZ" ),
( "Germany", "Flensburg", "FLF" ),
( "Italy - Peretola", "Florence", "FLR" ),
( "Colombia", "Florencia", "FLA" ),
( "Portugal", "Flores Island", "FLW" ),
( "Guatemala", "Flores", "FRS" ),
( "Brazil", "Florianopolis", "FLN" ),
( "Norway", "Floro", "FRO" ),
( "Italy", "Foggia", "FOG" ),
( "Norway", "Forde", "FDE" ),
( "Argentina", "Formosa", "FMA" ),
( "Madagascar", "Fort Dauphin", "FTU" ),
( "Martinique", "Fort De France", "FDF" ),
( "Brazil", "Fortaleza", "FOR" ),
( "Brazil", "Franca", "FRC" ),
( "Gabon", "Franceville", "MVB" ),
( "Botswana", "Francistown", "FRW" ),
( "Germany - Hahn", "Frankfurt", "HHN" ),
( "Germany - International", "Frankfurt", "FRA" ),
( "Denmark", "Fredericia", "ZBJ" ),
( "Bahamas", "Freeport", "FPO" ),
( "Sierra Leone - Lungi Intl", "Freetown", "FNA" ),
( "Germany", "Friedrichshafer", "FDH" ),
( "Spain", "Fuerteventura", "FUE" ),
( "Japan", "Fukuoka", "FUK" ),
( "Japan", "Fukue", "FUJ" ),
( "Japan", "Fukushima", "FKS" ),
( "Tuvalu", "Funafuti Atol", "FUN" ),
( "Portugal", "Funchal", "FNC" ),
( "Vanuatu", "Futuna Island", "FTA" ),
( "Wallis and Futuna Islands", "Futuna Island", "FUT" ),
( "China", "Fuyang", "FUG" ),
( "China", "Fuzhou", "FOC" ),
( "Botswana", "Gaborone", "GBE" ),
( "Tunisia", "Gafsa", "GAF" ),
( "Cote D'Ivoire", "Gagnoa", "GGN" ),
( "Ecuador", "Galapagos", "GPS" ),
( "Sweden", "Gallivare", "GEV" ),
( "Ireland", "Galway", "GWY" ),
( "Gabon", "Gamba", "GAX" ),
( "Ethiopia", "Gambela", "GMB" ),
( "Maldives", "Gan Island", "GAN" ),
( "South Korea", "Gangneung", "KAG" ),
( "Panama", "Garachine", "GHE" ),
( "Papua New Guinea", "Garaina", "GAR" ),
( "Papua New Guinea", "Garasa", "GRL" ),
( "Australia", "Garden Point", "GPN" ),
( "Cameroon", "Garoua", "GOV" ),
( "Saudi Arabia", "Gassim", "ELQ" ),
( "Vanuatu", "Gaua", "ZGU" ),
( "India", "Gawahati", "GAU" ),
( "Occupied Palestinian Territory", "Gaza City", "GZA" ),
( "Turkey", "Gaziatep", "GZT" ),
( "Poland", "Gdansk", "GDN" ),
( "Indonesia", "Gebe", "GEB" ),
( "Russia", "Gelendzik", "GDZ" ),
( "Sudan", "Geneina", "EGN" ),
( "Philippines", "General Santos", "GES" ),
( "Switzerland", "Geneva", "GVA" ),
( "Italy", "Genoa", "GOA" ),
( "Bahamas", "George Town", "GGT" ),
( "South Africa", "George", "GRJ" ),
( "Guyana", "Georgetown", "GEO" ),
( "", "Geraldton, Australia", "GET" ),
( "Spain", "Gerona", "GRO" ),
( "Libya", "Ghadames", "LTD" ),
( "Algeria", "Ghardala", "GHA" ),
( "Libya", "Ghat", "GHT" ),
( "Gibraltar", "Gibraltar", "GIB" ),
( "Pakistan", "Gilgit", "GIL" ),
( "New Zealand", "Gisborne", "GIS" ),
( "Saudi Arabia", "Gizan", "GIZ" ),
( "Solomon Islands", "Gizo", "GZO" ),
( "Australia", "Gladstone", "GLT" ),
( "United Kingdom - Glasgow International", "Glasgow", "GLA" ),
( "United Kingdom - Prestwick", "Glasgow", "PIK" ),
( "Australia", "Glen Innes", "GLI" ),
( "India", "Goa", "GOI" ),
( "Ethiopia", "Goba", "GOB" ),
( "Argentina", "Gobernador Gregores", "GGS" ),
( "Ethopia", "Gode/Iddidole", "GDE" ),
( "Brazil", "Goiania", "GYN" ),
( "Australia", "Gold Coast, QL", "OOL" ),
( "Costa Rica", "Golfito", "GLF" ),
( "China", "Golmud", "GOQ" ),
( "Papua New Guinea", "Gonalia", "GOE" ),
( "Ethiopia", "Gondari", "GDQ" ),
( "Ethiopia", "Gore", "GOR" ),
( "Papua New Guinea", "Goroka", "GKA" ),
( "Indonesia", "Gorontalo", "GTO" ),
( "Sweden - Landvetter", "Gothenburg", "GOT" ),
( "Sweden - Saeve", "Gothenburg", "GSE" ),
( "Australia", "Goulburn Island", "GBL" ),
( "Mali", "Goundam", "GUD" ),
( "Australia", "Gove", "GOV" ),
( "Bahamas", "Governors Harbour", "GHB" ),
( "Brazil", "Governador Valadares", "GVR" ),
( "Argentina", "Goya, CR", "OYA" ),
( "Malta", "Gozo", "GZM" ),
( "Portugal", "Graciosa Island", "GRW" ),
( "Australia", "Grafton", "GFN" ),
( "Spain", "Granada", "GRX" ),
( "Cayman Islands", "Grand Cayman", "GCM" ),
( "Turks and Caicos Islands", "Grand Turk Island", "GDT" ),
( "Austria", "Graz", "GRZ" ),
( "", "Grenada, Grenada", "GND" ),
( "France", "Grenoble", "GNB" ),
( "Australia", "Griffith", "GFF" ),
( "Iceland", "Grimsey", "GRY" ),
( "Greenland", "Groennedal", "JGR" ),
( "Netherlands", "Groningen", "GRQ" ),
( "Australia", "Groofe Eylandt", "GTE" ),
( "Mexico", "Guadalajara", "GDL" ),
( "Miconesia", "Guam", "GUM" ),
( "Honduras", "Guanaja", "GJA" ),
( "Mexico", "Guanajuato", "BJX" ),
( "China", "Guangzhou", "CAN" ),
( "Cuba", "Guantanamo", "GAO" ),
( "Guatemala", "Guatemala City", "GUA" ),
( "Ecuador", "Guayaquil", "GYE" ),
( "Bolivia", "Guayaramerin", "GYA" ),
( "Mexico", "Guaymas", "GYM" ),
( "United Kingdom", "Guernsey", "GCI" ),
( "Mexico", "Guerrero Negro", "GUB" ),
( "China", "Guilin", "KWL" ),
( "Venezuela", "Guiria", "GUI" ),
( "Uganda", "Gulu", "ULU" ),
( "China", "Gulyang", "KWE" ),
( "South Korea", "Gunsan", "KUV" ),
( "Saudi Arabia", "Gurayat", "URY" ),
( "Pakistan", "Gwadar", "GWD" ),
( "South Korea", "Gwangju", "KWJ" ),
( "India", "Gwalior", "GWL" ),
( "Azerbaijan", "Gyandzha", "KVD" ),
( "Armenia", "Gyourmri", "LWN" ),
( "Tonga", "HaApa", "HPA" ),
( "Japan", "Hachijo Jima", "HAC" ),
( "Sweden", "Hagfors", "HFS" ),
( "Israel", "Haifa", "HFA" ),
( "China", "Haikou", "HAK" ),
( "Saudi Arabia", "Hail", "HAS" ),
( "China", "Hailar", "HLD" ),
( "Viet Nam - Catbi", "Haiphong", "HPH" ),
( "Japan", "Hakodate", "HKD" ),
( "Germany", "Halberstadt", "ZHQ" ),
( "Australia", "Halls Creek", "HCQ" ),
( "Sweden", "Halmstad", "HAD" ),
( "Germany - Fuhisbuettel", "Hamburg", "HAM" ),
( "Germany - Luebeck", "Hamburg", "LBC" ),
( "Australia", "Hamilton Island", "HTI" ),
( "Bermuda", "Hamilton", "BDA" ),
( "New Zealand", "Hamilton", "HLZ" ),
( "Norway", "Hammerfest", "HFT" ),
( "China", "Hangzhou", "HGH" ),
( "Maldives", "Hanimaadhoo", "HAQ" ),
( "Viet Nam - Noibai", "Hanoi", "HAN" ),
( "Germany", "Hanover", "HAJ" ),
( "China", "Hanzhang", "HZG" ),
( "Zimbabwe", "Harare", "HRE" ),
( "China", "Harbin", "HRB" ),
( "Somolia", "Hargeisa", "HGA" ),
( "Norway", "Harstad-Narvik", "EVE" ),
( "Algeria", "Hassi Messaoud", "HME" ),
( "Norway", "Hasvik", "HAA" ),
( "Thailand", "Hat Yai", "HDY" ),
( "Japan", "Hateruma", "HTR" ),
( "Norway", "Haugesund", "HAU" ),
( "Cuba", "Havana", "HAV" ),
( "Australia", "Hayman Island", "HIS" ),
( "China", "Hefei", "HFE" ),
( "Germany", "Heidelberg", "HDB" ),
( "Germany", "Helgoland", "HGL" ),
( "Finland", "Helsinki", "HEL" ),
( "Myanmar", "Heno", "HEH" ),
( "Greece", "Heraklian", "HER" ),
( "Germany", "Heringsdorf", "HDF" ),
( "Sweden", "Hermavan", "HMV" ),
( "Mexico", "Hermosillo", "HMO" ),
( "Denmark", "Herning", "XAK" ),
( "Australia", "Hervey Bay", "HVB" ),
( "Japan - International", "Hiroshima", "HIJ" ),
( "Japan - Hiroshima West", "Hiroshima", "HIW" ),
( "Papua New Guinea", "Hivaro", "HIT" ),
( "Viet Nam", "Ho Chi Minh City", "SGN" ),
( "Australia", "Hobart", "HBA" ),
( "Yemen", "Hodeidah", "HOD" ),
( "South Africa", "Hoedspruit", "HDS" ),
( "Germany", "Hof", "HOQ" ),
( "Saudi Arabia", "Hofuf", "HOF" ),
( "China", "Hohhot", "HET" ),
( "New Zealand", "Hokitika", "HKK" ),
( "Cuba", "Holguin", "HOG" ),
( "Hong Kong", "Hong Kong", "HKG" ),
( "Solomon Islands", "Honiara", "HIR" ),
( "Norway", "Honningsvag", "HVG" ),
( "Australia", "Hooker", "HOK" ),
( "Australia", "Horn Island","HID" ),
( "Iceland", "Hornafjordur", "HFN" ),
( "Portugal", "Horta", "HOR" ),
( "Papua New Guinea", "Hoskins", "HKN" ),
( "China", "Hotan", "HTN" ),
( "Laos", "Houeisay", "HOE" ),
( "Libya", "Houn", "HUQ" ),
( "French Polynesia", "Huahine", "HUH" ),
( "Taiwan - Phi Bai", "Hualien", "HUN" ),
( "Thailand", "Hualtin", "HHQ" ),
( "French Polynesia", "Huanuco", "HUU" ),
( "China", "Huargyan", "HYN" ),
( "Mexico", "Huatulco", "HUX" ),
( "Sweden", "Hudiksvall", "HUV" ),
( "Viet Nam", "Hue", "HUI" ),
( "Australia", "Hughenden", "HGD" ),
( "Sweden", "Hultsfred", "HLF" ),
( "United Kingdom", "Humberside", "HUY" ),
( "Egypt", "Hurghada", "HRG" ),
( "Zimbabwe", "Hwange Nat Park", "HWN" ),
( "India", "Hyderabad", "HYD" ),
( "Romania", "Iasi", "IAS" ),
( "Colombia", "Ibague", "IBE" ),
( "Spain", "Ibiza", "IBZ" ),
( "Russia", "Igarka", "IAA" ),
( "Brazil", "Iguassu Falls, PR", "IGU" ),
( "Argentina", "Iguazu", "IGR" ),
( "Papua New Guinea", "Ihu", "IHU" ),
( "New Caledonia", "Ile Des Pins", "ILP" ),
( "Brazil", "Ilheus", "IOS" ),
( "Indonesia", "Illaga", "ILA" ),
( "Philippines - Mandurriao", "Iloilo", "ILO" ),
( "Indonesia", "Ilu", "IUL" ),
( "Greenland", "Ilulissat", "JAV" ),
( "Brazil", "Imperatriz", "IMP" ),
( "India", "Imphal", "IMF" ),
( "Algeria", "In Amenas", "IAM" ),
( "Bahamas", "Inagua", "IGA" ),
( "Indonesia", "Inanwatan", "INX" ),
( "Papua New Guinea", "Indagen", "IDN" ),
( "India", "Indore", "IDR" ),
( "Austria", "Innsbruck", "INN" ),
( "Russia", "Inta", "INA" ),
( "New Zealand", "Invercargill", "IVC" ),
( "Australia", "Inverell", "IVR" ),
( "United Kingdom", "Inverness", "INV" ),
( "Greece", "Ioannina", "IOA" ),
( "Papua New Guinea", "Ioma", "IOP" ),
( "Brazil", "Ipatinga", "IPN" ),
( "Colombia", "Ipiales", "IPI" ),
( "Philippines", "Ipil", "IPE" ),
( "Malaysia", "Ipoh", "IPH" ),
( "Vanuatu", "Ipota", "IPA" ),
( "Chile", "Iquique", "IQQ" ),
( "Peru", "Iquitos", "IQT" ),
( "Russia", "Irkutsk", "IKT" ),
( "Iceland", "Isafjordur", "IFJ" ),
( "Iran", "Isfahan", "IFN" ),
( "Japan", "Ishigakij", "ISG" ),
( "Pakistan", "Islamabad", "ISB" ),
( "Canada", "Island Lake/Garden Hill", "YIV" ),
( "United Kingdom", "Islay", "ILY" ),
( "United Kingdom", "Isle of Man", "IOM" ),
( "United Kingdom - St Marys", "Isles of Scilly", "ISC" ),
( "United Kingdom - Tresco", "Isles of Scilly", "TSO" ),
( "Turkey", "Istanbul", "IST" ),
( "Brazil", "Itaituba", "ITB" ),
( "Papua New Guinea", "Itokama", "ITK" ),
( "Finland", "Ivalo", "IVL" ),
( "Ukraine", "Ivano-Frankovsk", "IFO" ),
( "Japan", "Iwami", "IWJ" ),
( "Mexico", "Ixtapa", "ZIH" ),
( "Mexico", "Ixtepec", "IZT" ),
( "Turkey", "Izmir", "ADB" ),
( "Japan", "Izumo", "IZO" ),
( "Marshall Islands", "Jabor", "JAT" ),
( "Brazil", "Jacareacanga", "JCR" ),
( "Pakistan", "Jacobabad", "JAG" ),
( "Papua New Guinea", "Jacquinot Bay", "JAQ" ),
( "India", "Jaipur", "JAI" ),
( "Indonesia", "Jakarta", "CGK" ),
( "Mexico", "Jalapa", "JAL" ),
( "Marshall Islands", "Jaluit Island", "UIT" ),
( "Indonesia", "Jambi",  "DJB" ),
( "India", "Jamnagar", "JGA" ),
( "Nepal", "Janakpur", "JKR" ),
( "Panama", "Jaque", "JQE" ),
( "Indonesia", "Jayapura", "DJJ" ),
( "Saudi Arabia", "Jeddah", "JED" ),
( "Marshall Islands", "Jeh", "JEJ" ),
( "metro area", "Jeju, South Korea - Jeju Airport", "CJU" ),
( "Spain", "Jerez De La Frontere", "XRY" ),
( "United Kingdom", "Jersey", "JER" ),
( "Bangladesh", "Jessore", "JSR" ),
( "China", "Jiamusi", "JMU" ),
( "China", "Jiayuguan", "JGN" ),
( "Algeria", "Jijel", "GJL" ),
( "Ethiopia", "Jijiga", "JIJ" ),
( "Ethiopia", "Jimma", "JIM" ),
( "China", "Jinan", "TNA" ),
( "China", "Jingdezhen", "JDZ" ),
( "China", "Jinghong", "JHG" ),
( "Uganda", "Jinja", "JIN" ),
( "China", "Jinjiang", "JJN" ),
( "South Korea - Sancheon", "Jinju", "HIN" ),
( "Ethiopia", "Jinka", "BCO" ),
( "China", "Jinzhou", "JNZ" ),
( "Brazil", "Ji-Parana", "JPR" ),
( "Pakistan", "Jiwani", "JIW" ),
( "Brazil", "Joao Pessoa", "JPA" ),
( "India", "Jodhpur", "JDH" ),
( "Finland", "Joensuu", "JOE" ),
( "South Africa", "Johannesburg", "JNB" ),
( "US Minor Outlying Islands", "Johnston Island", "JON" ),
( "Malaysia", "Johor", "JHB" ),
( "Brazil", "Joinville", "JOI" ),
( "India", "Jommu", "IXJ" ),
( "Nepal", "Jomsom", "JMO" ),
( "Sweden", "Jonkoping", "JKG" ),
( "India", "Jorhat", "JRH" ),
( "Argentina", "Jose De San Martin", "JSM" ),
( "Saudi Arabia", "Jouf", "AJF" ),
( "Brazil", "Juazeiro Do Norte", "JDO" ),
( "Germany", "Juist", "JUI" ),
( "Brazil", "Juiz De Fora", "JDF" ),
( "Argentina", "Jujuy", "JUJ" ),
( "Australia", "Julia Creek", "JCK" ),
( "Peru", "Juliaca", "JUL" ),
( "China", "Juzha", "JUZ" ),
( "Finland", "Jyvaskyla", "JYV" ),
( "Maldives", "Kaadedhdhoo", "KDM" ),
( "Marshall Islands", "Kaben", "KBT" ),
( "Ethiopia", "Kabri Dar", "ABK" ),
( "Afghanistan", "Kabul", "KBL" ),
( "Papua New Guinea", "Kabwun", "KBM" ),
( "Pakistan", "Kadanwari", "KCF" ),
( "Maldives", "Kadhonoo", "KDO" ),
( "Papua New Guinea", "Kaintiba", "KZF" ),
( "New Zealand", "Kaitaia", "KAT" ),
( "Finland", "Kajaani", "KAJ" ),
( "Australia", "Kalbarri", "KAX" ),
( "Russia", "Kaliningrad", "KGD" ),
( "Indonesia", "Kambuaya", "KBX" ),
( "Syrian Arab Republic", "Kameshli", "KAC" ),
( "Indonesia", "Kamur", "KCD" ),
( "Papua New Guinea", "Kamusi", "KUY" ),
( "Nigeria", "Kano", "KAN" ),
( "Pakistan - Quaid-E-Azam International", "Karachi", "KHI" ),
( "Estonia", "Kardia", "KDL" ),
( "Zimbabwe", "Kariba", "KAB" ),
( "Germany", "Karlsruhe/Badern Baden", "FKB" ),
( "Greece", "Karpathos", "AOK" ),
( "Indonesia", "Karubaga", "KBF" ),
( "Zambia", "Kasaba Bay", "ZKB" ),
( "Zambia", "Kasama", "KAA" ),
( "Botswana", "Kasane", "BBK" ),
( "Australia", "Katherine, NT", "KTR" ),
( "Nepal", "Kathmandu", "KTM" ),
( "Poland", "Katowice", "KTW" ),
( "Lithuania", "Kaunas", "KUN" ),
( "Greece", "Kavala", "KVA" ),
( "Papua New Guinea", "Kavieng", "KVG" ),
( "Myanmar", "Kawthaung", "KAW" ),
( "Turkey", "Kayseri", "ASR" ),
( "Russia", "Kazan,", "KZN" ),
( "Greece", "Kefallinia", "EFL" ),
( "Indonesia", "Kendari", "KDI" ),
( "Greece", "Kerkyra", "CFU" ),
( "India", "Khajuraho", "HJR" ),
( "Egypt", "Kharga", "UVL" ),
( "Ukraine", "Kharkov", "HRK" ),
( "Tajikistan", "Khudzhand", "LBD" ),
( "Pakistan", "Khuzdar", "KDD" ),
( "Ukraine - Zhulhany", "Kiev", "IEV" ),
( "Ukraine - Borispol", "Kiev", "KBP" ),
( "Rwanda", "Kigali", "KGL" ),
( "Tanzania", "Kigoma", "TKQ" ),
( "Tanzania", "Kilimanjaro", "JRO" ),
( "Canada", "Kimmirut/Lake Harbour", "YLC" ),
( "Jamaica - Norman Manley", "Kingston", "KIN" ),
( "Jamaica - Tinson", "Kingston", "KTP" ),
( "Congo", "Kinshasa", "FIH" ),
( "Solomon Islands", "Kirakira", "IRA" ),
( "Japan", "Kitadaito", "KTD" ),
( "Finland", "Kittila", "KTT" ),
( "Papua New Guinea", "Kiunga", "UNG" ),
( "Kenya", "Kiwayu", "KWY" ),
( "Ireland", "Knock", "NOC" ),
( "Japan", "Kochi", "KCZ" ),
( "Thailand", "Koh Samui", "USM" ),
( "India", "Kolkata", "CCU" ),
( "Poland", "Kolobrzeg", "QJY" ),
( "Russia", "Komsomolsk Na Amure", "KXK" ),
( "Turkey", "Konya", "KYA" ),
( "Palau", "Koror", "ROR" ),
( "Poland", "Koszalin", "OSZ" ),
( "Malaysia", "Kota Bharu", "KBR" ),
( "Malaysia", "Kota Kinabalu", "BKI" ),
( "Australia", "Kowanyama, QL", "KWM" ),
( "India", "Kozhikode", "CCJ" ),
( "Thailand", "Krabi", "KBV" ),
( "Poland", "Krakow", "KRK" ),
( "Ukraine", "Krivoy Rog", "KWG" ),
( "Malaysia", "Kuala Lumpur", "KUL" ),
( "Malaysia", "Kuala Terengganu", "TGG" ),
( "Malaysia", "Kuantan", "KUA" ),
( "Australia", "Kubin Island, QL", "KUG" ),
( "Malaysia", "Kuching", "KCH" ),
( "Turkey", "Kahramanmaras", "KCM" ),
( "Malaysia", "Kudat", "KUD" ),
( "Libya", "Kufrah", "AKF" ),
( "Greenland", "Kulusuk", "KUS" ),
( "Japan", "Kumejima", "UEO" ),
( "Papau New Guinea", "Kundiawa", "CMU" ),
( "Finland", "Kuopio", "KUO" ),
( "Papua New Guinea", "Kuri", "KUQ" ),
( "Japan", "Kushiro", "KUH" ),
( "Georgia", "Kutaisi", "KUT" ),
( "Finland", "Kuusamo", "KAO" ),
( "Kuwait", "Kuwait", "KWI" ),
( "Marshall Islands", "Kwajalein", "KWA" ),
( "Russia", "Kyzyl", "KYZ" ),
( "Honduras", "La Ceiba", "LCE" ),
( "Spain", "La Coruna", "LCG" ),
( "Panama", "La Palma", "PLP" ),
( "Bolivia", "La Paz", "LPB" ),
( "Mexico", "La Paz", "LAP" ),
( "Argentina", "La Rioja", "IRJ" ),
( "Dominican Republic", "La Romana", "LRM" ),
( "Chile", "La Serena", "LSC" ),
( "Morocco", "Laayoune", "EUN" ),
( "Fiji", "Labasa", "LBS" ),
( "Papua New Guinea", "Lablab", "LAB" ),
( "Indonesia", "Labuan Bajo", "LBJ" ),
( "Malaysia", "Labuan", "LBU" ),
( "Marshall Islands", "Lae Island", "LML" ),
( "Papua New Guinea", "Lae", "LAE" ),
( "Brazil", "Lages, SC", "LAJ" ),
( "Ecuador", "Lago Agrio", "LGQ" ),
( "Argentina", "Lago Argentina", "ING" ),
( "Nigeria", "Lagos", "LOS" ),
( "Malaysia", "Lahadbatu", "LDU" ),
( "Pakistan", "Lahore", "LHE" ),
( "Fiji", "Lakeba", "LKB" ),
( "Norway", "Lakselv", "LKL" ),
( "Ethiopia", "Lalibela", "LLI" ),
( "Vanuatu", "Lamap", "LPM" ),
( "Vanuatu", "Lamen Bay", "LNB" ),
( "Italy", "Lamezia-Terme", "SUF" ),
( "Thailand", "Lampang", "LPI" ),
( "Italy", "Lampedusa", "LMP" ),
( "Kenya", "Lamu", "LAU" ),
( "United Kingdom", "Lands End", "LEQ" ),
( "Indonesia", "Langguri", "LUV" ),
( "Malaysia", "Langkawi", "LGK" ),
( "France", "Lannion", "LAI" ),
( "Spain", "Lanzarote", "ACE" ),
( "Guinea", "Lanzhau", "LHW" ),
( "China", "Lanzhou", "ZGC" ),
( "Philippines", "Laoag", "LAO" ),
( "Finland", "Lappeenranta", "LPP" ),
( "Indonesia", "Larantuka", "LKA" ),
( "Cyprus", "Larnaca", "LCA" ),
( "France", "Larochelle", "LRH" ),
( "Spain", "Las Palmas", "LPA" ),
( "Venezuela", "Las Piedras", "LSP" ),
( "Syria", "Latakia", "LTK" ),
( "Fiji", "Laucala Island", "LUC" ),
( "Australia", "Launceston, TS", "LST" ),
( "Angola", "Luanda", "LAD" ),
( "Australia", "Laverton, WA", "LVO" ),
( "Malaysia", "Lawas", "LWY" ),
( "France", "Le Havre", "LEH" ),
( "France", "Le Mans", "ZLN" ),
( "France", "Le Puy", "LPY" ),
( "France", "Le Touquet", "LTQ" ),
( "Australia", "Learmonth, WA", "LEA" ),
( "United Kingdom", "Leeds", "LBA" ),
( "Philippines", "Legaspi", "LGP" ),
( "India", "Leh", "IXL" ),
( "Australia", "Leinster, WA", "LER" ),
( "Germany", "Leipzig", "LEJ" ),
( "Norway", "Leknes", "LKN" ),
( "Greece", "Lemnos", "LXS" ),
( "Mexico", "Leon", "BJX" ),
( "Australia", "Leonora, WA", "LNO" ),
( "Colombia", "Leticia", "LET" ),
( "China", "Lhasa", "LXA" ),
( "China", "Lianyungang", "LYG" ),
( "Costa Rica", "Liberia", "LIR" ),
( "Gabon", "Libreville", "LBV" ),
( "Mozambique", "Lichinga", "VXC" ),
( "Belgium", "Liege", "LGG" ),
( "New Caledonia", "Lifa", "LIF" ),
( "Australia", "Lightning Ridge, NS", "LHG" ),
( "Papua New Guinea", "Lihir Island", "LNV" ),
( "China", "Lijiang City", "LJG" ),
( "Marshall Islands", "Likiep Island", "LIK" ),
( "France - Lesquin", "Lille", "LIL" ),
( "France - Rail service", "Lille", "XDB" ),
( "Malawi", "Lilongwe", "LLW" ),
( "Peru", "Lima", "LIM" ),
( "Malaysia", "Limbang", "LMN" ),
( "France", "Limoges", "LIG" ),
( "Australia", "Lindeman Island, QL", "LDC" ),
( "Tanzania", "Lindi", "LDI" ),
( "Sweden", "Linkoping", "LPI" ),
( "China", "Linyi", "LYI" ),
( "Austria", "Linz", "LNZ" ),
( "Portugal", "Lisbon", "LIS" ),
( "Australia", "Lismore, NS", "LSY" ),
( "China", "Liuzhou", "LZH" ),
( "United Kingdom", "Liverpool", "LPL" ),
( "Zambia", "Livingstone", "LVI" ),
( "Australia", "Lizard Island, QL", "LZR" ),
( "Slovenia", "Ljubliana", "LJU" ),
( "Australia", "Lockhart River", "IRG" ),
( "Marshall Islands", "Loen", "LOF" ),
( "Ecuador", "Loja", "LOH" ),
( "Togo", "Lome", "LFW" ),
( "United Kingdom - All airports", "London", "LON" ),
( "United Kingdom - Biggin Hill", "London", "BQH" ),
( "United Kingdom - Gatwick", "London", "LGW" ),
( "United Kingdom - Heathrow", "London", "LHR" ),
( "United Kingdom - London City", "London", "LCY" ),
( "United Kingdom - Luton", "London", "LTN" ),
( "United Kingdom - Stansted", "London", "STN" ),
( "United Kingdom", "Londonderry", "LDY" ),
( "United Kingdom - Rail service", "London-Paddington", "QQP" ),
( "Brazil", "Londrina, PR", "LDB" ),
( "Indonesia", "Long Apung", "LPU" ),
( "Malaysia", "Long Banga", "LBP" ),
( "Indonesia", "Long Bawan", "LBW" ),
( "Australia", "Long Island", "HAP" ),
( "Bahamas", "Long Island/Deadmans Cay", "LGI" ),
( "Malaysia", "Long Lellang", "LGL" ),
( "Malaysia", "Long Seridan", "ODN" ),
( "Vanuatu", "Longana", "LOD" ),
( "Australia", "Longreach, QL", "LRE" ),
( "Svalbard & Jan Mayen Island", "Longyearbyen", "LYR" ),
( "Vanuatu", "Lonorore", "LNE" ),
( "Australia", "Lord Howe Island, NS", "LDH" ),
( "Mexico", "Loreto", "LTO" ),
( "France", "Lorient", "LRT" ),
( "Mexico", "Los Cabos", "SJD" ),
( "Mexico", "Los Mochis", "LMM" ),
( "Papua New Guinea", "Losuia", "LSA" ),
( "France", "Lourdes/Tarbes", "LDE" ),
( "Mexico", "Lozaro Cardenas", "LZC" ),
( "Angola", "Luanda", "LAD" ),
( "Laos", "Luang Namtha", "LXG" ),
( "Laos", "Luang Prabang", "LPQ" ),
( "India", "Lucknow", "LKO" ),
( "Namibia", "Luderitz", "LUD" ),
( "Switzerland", "Lugano", "LUG" ),
( "Uganda", "Lugansk", "VSG" ),
( "Nepal", "Lukla", "LUA" ),
( "Sweden", "Lulea", "LLA" ),
( "Congo", "Lumbashi", "FBM" ),
( "China", "Luoyang", "LYA" ),
( "Zambia", "Lusaka", "LUN" ),
( "Indonesia", "Luwuk", "LUW" ),
( "Luxembourg", "Luxembourg", "LUX" ),
( "China", "Luxi", "LUM" ),
( "Egypt", "Luxor", "LXR" ),
( "China", "Luzhou", "LZO" ),
( "Ukraine", "Lvov", "LWO" ),
( "Sweden", "Lyoksele", "LYC" ),
( "France - Satolas", "Lyon", "LYS" ),
( "France - Lyon Part-Dieu Rail service", "Lyon", "XYD" ),
( "Netherlands", "Maastricht", "MST" ),
( "Australia", "Mabuiag Island, QL", "UBB" ),
( "Brazil", "Macapa, AP", "MCP" ),
( "Ecuador", "Macas", "XMS" ),
( "China", "Macau", "MFM" ),
( "Brazil", "Maceio, AL", "MCZ" ),
( "Ecuador", "Machala", "MCH" ),
( "Australia", "Mackay, QL", "MKY" ),
( "Papua New Guinea", "Madang", "MAG" ),
( "Saudi Arabia", "Madinah", "MED" ),
( "Spain", "Madrid", "MAD" ),
( "India", "Madurai", "IXM" ),
( "Thailand", "Mae Hong Son", "HGN" ),
( "Thailand", "Mae Sot", "MAQ" ),
( "Vanuatu", "Maewo", "MWF" ),
( "Tanzania", "Mafia", "MFA" ),
( "Russia", "Magadan", "GDX" ),
( "Russia", "Magnitogorsk", "MQF" ),
( "Madagascar", "Mahanoro", "VVB" ),
( "Seychelles", "Mahe Island", "SEZ" ),
( "Madagascar", "Maintirano", "MXT" ),
( "Cape Verde", "Maio", "MMO" ),
( "Marshall Islands", "Majkin", "MJE" ),
( "Madagascar", "Majunga", "MJN" ),
( "Marshall Islands", "Majuro", "MAJ" ),
( "Ethiopia", "Makale", "MQX" ),
( "Russia", "Makhachkala", "MCX" ),
( "Gabon", "Makokou", "MKU" ),
( "Taiwan", "Makung", "MZG" ),
( "Equatorial Guinea", "Malabo", "SSG" ),
( "Malaysia", "Malacca", "MKZ" ),
( "Spain", "Malaga", "AGP" ),
( "Sudan", "Malakai", "MAK" ),
( "Argentina", "Malargue, MD", "LGS" ),
( "Turkey", "Malatya", "MLX" ),
( "Maldives", "Male", "MLE" ),
( "Kenya", "Malindi", "MYD" ),
( "Sweden", "Malmo", "MMX" ),
( "Marshall Islands", "Maloelap Island", "MAV" ),
( "Fiji", "Malololailai", "PTF" ),
( "Malta", "Malta", "MLA" ),
( "Madagascar", "Mampikony", "WMP" ),
( "Fiji", "Mana Island", "MNF" ),
( "Indonesia", "Manado", "MDC" ),
( "Nicaragua", "Managua", "MGA" ),
( "Madagascar", "Manakara", "WVK" ),
( "Madagascar", "Mananara", "WMR" ),
( "Nepal", "Manang", "NGX" ),
( "Madagascar", "Mananjary", "MNJ" ),
( "Brazil", "Manaus, AM", "MAO" ),
( "United Kingdom", "Manchester", "MAN" ),
( "Myanmar", "Mandalay", "MDL" ),
( "Madagascar", "Mandritsara", "WMA" ),
( "Cook Islands", "Mangaia Island", "MGS" ),
( "India", "Mangalore", "IXE" ),
( "Bahamas", "Mangrove Cay", "MAY" ),
( "Zambia", "Mangu", "MNR" ),
( "Papua New Guinea", "Manguna", "MFO" ),
( "French Polynesia", "Manihi", "XMH" ),
( "Cook Islands", "Manihiki Island", "MHX" ),
( "Philippines", "Manila", "MNL" ),
( "Australia", "Maningrioa, NT", "MNG" ),
( "Colombia", "Manizales", "MZL" ),
( "Madagascar", "Manja", "MJA" ),
( "Germany", "Mannheim", "MHG" ),
( "Indonesia", "Manokwari", "MKW" ),
( "United Kingdom", "Manston", "MSE" ),
( "Ecuador", "Manta", "MEC" ),
( "Papua New Guinea", "Manus Island", "MAS" ),
( "Cuba", "Manzanillo", "MZO" ),
( "Mexico", "Manzanillo", "ZLO" ),
( "Swaziland", "Manzini", "MTS" ),
( "Chad", "Mao", "AMO" ),
( "Western Samoa", "Maota Savaii Is", "MXS" ),
( "Mozambique", "Maputo", "MPM" ),
( "Argentina", "Mar Del Plata, BA", "MDQ" ),
( "Kenya", "Mara Lodges", "MRE" ),
( "Brazil", "Maraba, PA", "MAB" ),
( "Venezuela", "Maracaibo", "MAR" ),
( "Venezuela", "Maracay", "MYC" ),
( "New Caledonia", "Mare", "MEE" ),
( "South Africa", "Margate", "MGH" ),
( "Slovenia", "Maribor", "MBX" ),
( "Finland", "Mariehamn", "MHQ" ),
( "Greenland", "Mariitsoq", "JSU" ),
( "Brazil", "Marilia, SP", "MII" ),
( "Brazil", "Maringa, PR", "MGF" ),
( "Ukraine", "Mariupol", "MPW" ),
( "Madagascar", "Maroantsetra", "WMN" ),
( "Cameroon", "Marova", "MVR" ),
( "France", "Marseille", "MRS" ),
( "Bahamas", "Marsh Harbour", "MHH" ),
( "Malaysia", "Marudi", "MUR" ),
( "Australia", "Maryborough, QL", "MBH" ),
( "Philippines", "Masbate", "MBT" ),
( "Lesotho", "Maseru", "MSU" ),
( "Iran", "Mashad", "MHD" ),
( "Mexico", "Matamoros", "MAM" ),
( "Indonesia", "Mataram", "AMI" ),
( "Japan", "Matsumoto", "MMJ" ),
( "Japan", "Matsuyama", "MYJ" ),
( "Venezuela", "Maturin", "MUN" ),
( "Cook Islands", "Mauke Island", "MUK" ),
( "Myanmar", "Maulmyine", "MNU" ),
( "Indonesia", "Maumere", "MOF" ),
( "Botswana", "Maun", "MUB" ),
( "French Polynesia", "Maupiti", "MAU" ),
( "Mauritius", "Mauritius", "MRU" ),
( "Bahamas", "Mayaguana", "MYG" ),
( "Puerto Rico", "Mayaguez", "MAZ" ),
( "Mexico", "Mazatlan", "MZT" ),
( "Congo", "Mbandaka", "MDK" ),
( "Congo", "Mbuji Mayi", "MJM" ),
( "Australia", "Mcarthur River, NT", "MCV" ),
( "Indonesia", "Medan", "MES" ),
( "Colombia - Enrique Olaya Herrera", "Medellin", "EOH" ),
( "Colombia - Jose Marie Cordova", "Medellin", "MDE" ),
( "Australia", "Meekatharra, WA", "MKR" ),
( "Norway", "Mehamn", "MEH" ),
( "China", "Meixian", "MXZ" ),
( "Marshall Islands", "Mejit Island", "MJB" ),
( "Ethiopia", "Mekane Selam", "MKS" ),
( "Australia", "Melbourne, Victoria", "MEL" ),
( "Spain", "Melilla", "MLN" ),
( "Japan", "Memanbetsu", "MMB" ),
( "Ethiopia", "Mendi", "NDM" ),
( "Papua New Guinea", "Mendi", "MDU" ),
( "Argentina", "Mendoza, MD", "MDZ" ),
( "Spain", "Menorca", "MAH" ),
( "Papua New Guinea", "Menyamya", "MYX" ),
( "Indonesia", "Merauke", "MKQ" ),
( "Sudan", "Merave", "MWE" ),
( "Indonesia", "Merdey", "RDE" ),
( "Mexico", "Merida", "MID" ),
( "Venezuela", "Merida", "MRD" ),
( "Australia", "Merimbula, NS", "MIM" ),
( "Egypt", "Mersa Matruh", "MUH" ),
( "France", "Metz/Nancy", "ETZ" ),
( "Mexico", "Mexicali", "MXL" ),
( "Mexico", "Mexico City", "MEX" ),
( "Zambia", "Mfume", "MFU" ),
( "Madagascar", "Miandrivazo", "ZVA" ),
( "Turks and Caicos", "Middle Caicos", "MDS" ),
( "US Minor Outlying Islands", "Midway Island", "MDY" ),
( "Finland", "Mikkeli", "MIK" ),
( "Greece", "Mikonos", "JMK" ),
( "Italy - Orio Al Serio", "Milan", "BGY" ),
( "Italy - Linate", "Milan", "LIN" ),
( "Italy - Malpensa", "Milan", "MXP" ),
( "Italy - Parma", "Milan", "PMF" ),
( "Australia", "Mildura, VI", "MQL" ),
( "Marshall Islands", "Mili Island", "MIJ" ),
( "Australia", "Milingimbi, NT", "MGT" ),
( "Japan", "Minami Daito", "MMD" ),
( "Mexico", "Minatitla", "MTT" ),
( "Indonesia", "Mindiptana", "MDP" ),
( "Russia", "Mineralnye Vody", "MRV" ),
( "Belarus - Minsk International 1", "Minsk", "MHP" ),
( "Belarus - Minsk International 2", "Minsk", "MSQ" ),
( "Malaysia", "Miri", "MYY" ),
( "Russia", "Mirnyj", "MJZ" ),
( "Japan", "Misawa", "MSJ" ),
( "Papua New Guinea", "Misima Island", "MIS" ),
( "Libya", "Misurata", "MRA" ),
( "Cook Islands", "Mitiaro Island", "MOI" ),
( "Japan", "MiyakeJima", "MYE" ),
( "Japan", "Miyako Jima", "MMY" ),
( "Ethiopia", "Mizan Teferi", "MTF" ),
( "Norway", "Mo I Rana", "MQN" ),
( "Cuba", "Moa", "MOA" ),
( "Fiji", "Moala", "MFJ" ),
( "Indonesia", "Moanamani", "ONI" ),
( "Congo", "Moanda", "MNB" ),
( "Gabon", "Moanda", "MFF" ),
( "Somalia", "Mogadishu", "MGQ" ),
( "Denmark", "Mohenjodaro", "MJD" ),
( "South Korea", "Mokpo", "MPK" ),
( "Namibia", "Mokuti Lodge", "OKU" ),
( "Norway", "Molde", "MOL" ),
( "Kenya", "Mombasa", "MBA" ),
( "Tunisia", "Monastir", "MIR" ),
( "Japan", "Monbetsu", "MBE" ),
( "Mexico", "Monclova", "LOV" ),
( "Australia", "Monkey Mia, WA", "MJK" ),
( "Solomon Islands", "Mono", "MNY" ),
( "Liberia", "Monrovia", "ROB" ),
( "Monaco", "Monte Carlo", "MCM" ),
( "Brazil", "Monte Dourado, PA", "MEU" ),
( "Jamaica", "Montego Bay", "MBJ" ),
( "Colombia", "Monteria", "MTR" ),
( "Mexico", "Monterrey", "MTY" ),
( "Brazil", "Montes Claros, MG", "MOC" ),
( "Uruguay", "Montevideo", "MVD" ),
( "France", "Montpellier", "MPL" ),
( "Montserrat", "Montserrat", "MNI" ),
( "French Polynesia", "Moorea", "MOZ" ),
( "Mali", "Mopti", "MZI" ),
( "Sweden", "Mora", "MXX" ),
( "Madagascar", "Morafenobe", "TVA" ),
( "Madagascar", "Morambe", "MXM" ),
( "Australia", "Moranbah, QL", "MOV" ),
( "Australia", "Moree, NS", "MRZ" ),
( "Mexico", "Morelia", "MLM" ),
( "Japan", "Morioka", "HNA" ),
( "Australia", "Mornington, QL", "ONG" ),
( "Papua New Guinea", "Moro", "MXH" ),
( "Madagascar", "Morondava", "MOQ" ),
( "Comoros", "Moroni", "HAH" ),
( "Australia", "Moruya, NS", "MYA" ),
( "Russia - all locations", "Moscow", "MOW" ),
( "Russia - Bykovo", "Moscow", "BKA" ),
( "Russia - Domodedovo", "Moscow", "DME" ),
( "Russia - Sheremetyevo", "Moscow", "SVO" ),
( "Russia - Vnukovo", "Moscow", "VKO" ),
( "Norway", "Mosjoen", "MJF" ),
( "Bosnia and Herzegovina", "Mostar", "OMO" ),
( "Vanuatu", "Mota Lava", "MTV" ),
( "Gabon", "Mouila", "MJL" ),
( "New Zealand", "Mount Cook", "MON" ),
( "Australia", "Mount Gambier, SA", "MGB" ),
( "Papua New Guinea", "Mount Hagen", "HGU" ),
( "Australia", "Mount Hotham, VI", "MHU" ),
( "Australia", "Mount Isa", "ISA" ),
( "Australia", "Mount Keith, WA", "WME" ),
( "Australia", "Mount Magnet, WA", "MMG" ),
( "Falkland Islands", "Mount Pleasant", "MPN" ),
( "Namibia", "Mpacha", "MPA" ),
( "Tanzania", "Mtwara", "MYW" ),
( "Brazil", "Mucuri, BA", "MVS" ),
( "China", "Mudanjiang", "MDG" ),
( "Australia", "Mudgee", "DGE" ),
( "Germany", "Muenster", "FMO" ),
( "Malaysia", "Mukan", "MKM" ),
( "France", "Mulhouse", "MLH" ),
( "Indonesia", "Mulia", "LII" ),
( "Pakistan", "Multan", "MUX" ),
( "Malaysia", "Mulu", "MZV" ),
( "India", "Mumbai", "BOM" ),
( "Solomon Islands", "Munda", "MUA" ),
( "Germany", "Munich", "MUC" ),
( "Spain", "Murcia", "MJV" ),
( "Russia", "Murmansk", "MMK" ),
( "Australia", "Murray Island, QL", "MYI" ),
( "Turkey", "Mus", "MSR" ),
( "Oman", "Muscat", "MCT" ),
( "Tanzania", "Musoma", "MUZ" ),
( "Pakistan", "Muzaffarabad", "MFG" ),
( "Tanzania", "Mwanza", "MWZ" ),
( "Myanmar", "Myeik", "MGZ" ),
( "Myanmar", "Myitkyina", "MYT" ),
( "Greece", "Mytilene", "MJT" ),
( "Malawi", "Mzuzu", "ZZU" ),
( "Indonesia", "Nabire", "NBX" ),
( "Mozambique", "Nacala", "MNC" ),
( "Morocco", "Nadar", "NDR" ),
( "Fiji", "Nadi", "NAN" ),
( "Russia", "Nadym", "NYM" ),
( "Philippines", "Naga", "WNP" ),
( "Japan", "Nagasaki", "NGS" ),
( "Japan - Chubu CentrAir Intl", "Nagoya", "NGO" ),
( "Japan - Nagoya Komaki APT", "Nagoya", "NGO" ),
( "India", "Nagpur", "NAG" ),
( "Kenya - Jomo Kenyatta Intl", "Nairobi", "NBO" ),
( "Kenya - Wilson", "Nairobi", "WIL" ),
( "Azerbaijan", "Nakhichevan", "NAJ" ),
( "Thailand", "Nakhon Ratchosima", "NAK" ),
( "Thailand", "Nakhon Si Thammarat", "NST" ),
( "Russia", "Nalchik", "NAL" ),
( "Uzbekistan", "Namangan", "NMA" ),
( "Papua New Guinea", "Namatana", "ATN" ),
( "Marshall Islands", "Namorik Island", "NDK" ),
( "Mozambique", "Nampula", "APL" ),
( "Norway", "Namsos", "OSY" ),
( "Papua New Guinea", "Namudi", "NDI" ),
( "Thailand", "Nan", "NNT" ),
( "China", "Nanchong", "NAO" ),
( "China", "Nanking/Nanjing", "NKG" ),
( "China", "Nanning", "NNG" ),
( "Greenland", "Nanortalik", "JNN" ),
( "France - Nantes Atlantique", "Nantes", "NTE" ),
( "France - Rail service", "Nantes", "QJZ" ),
( "China", "Nantong", "NTG" ),
( "China", "Nanyang", "NNY" ),
( "Kenya", "Nanyuki", "NYK" ),
( "New Zealand", "Napier-Hastings", "NPE" ),
( "Italy", "Naples", "NAP" ),
( "Thailand", "Narathiwat", "NAW" ),
( "Australia", "Narrabri, NS", "NAA" ),
( "Greenland", "Narsaq", "JNS" ),
( "Greenland", "Narsarsuaq", "UAK" ),
( "Norway", "Narvik", "NVK" ),
( "Russia", "Naryan-Mar", "NNM" ),
( "Bahamas - Paradise Island", "Nassau", "NAS" ),
( "Congo", "Natadi", "MAT" ),
( "Brazil", "Natal, RN", "NAT" ),
( "Nauru", "Nauru Island", "INU" ),
( "Brazil", "Navegantes, SC", "NVT" ),
( "Pakistan", "Nawabshah", "WNS" ),
( "Russia", "NayUrengoy", "NUX" ),
( "Zambia", "Ndola", "NLA" ),
( "Greenland", "Neerlerit Inaat", "CNP" ),
( "Russia", "Nefteyugansk", "NFG" ),
( "Ethiopia", "Neghelli", "EGL" ),
( "Jamaica", "Negril", "NEG" ),
( "Colombia", "Neiva", "NVA" ),
( "Saudi Arabia", "Nejran", "EAM" ),
( "New Zealand", "Nelso", "NSN" ),
( "South Africa", "Nelspruit", "NLP" ),
( "Mauritania", "Nema", "EMN" ),
( "Russia", "Neryjungri", "NER" ),
( "Argentina", "Neuquen, NE", "NQN" ),
( "St. Kitts and Nevis", "Nevis", "NEV" ),
( "Grat Bitain", "London/Groton", "GON" ),
( "New Zealand", "New Plymouth", "NPL" ),
( "Australia - Belmont", "Newcastle, New South Wales", "BEO" ),
( "Australia", "Newcastle, New South Wales", "NTL" ),
( "United Kingdom", "Newcastle", "NCL" ),
( "Australia", "Newman, WA", "ZNE" ),
( "United Kingdom", "Newquay", "NQY" ),
( "Cameroon", "Ngaoundere", "NGE" ),
( "Fiji", "Ngau Island", "NGI" ),
( "Australia", "Ngukurr, NT", "RPM" ),
( "Viet Nam", "Nha Trang", "NHA" ),
( "Niger", "Niamey", "NIM" ),
( "France", "Nice", "NCE" ),
( "Cyprus", "Nicosia", "NIC" ),
( "France", "Nimes", "FNI" ),
( "China", "Ningbo", "NGB" ),
( "Congo", "Nioko", "NIX" ),
( "Tonga", "Niuafo'ou", "NFO" ),
( "Tonga", "Niuatoputapu", "NTT" ),
( "Niue", "Niue Island", "IUE" ),
( "Russia", "Nizhnevartovsk", "NJC" ),
( "Russia", "Nizhniy Novgorod", "GOJ" ),
( "Russia", "Nojabrxsk", "NOJ" ),
( "Chad", "Ndjamena", "NDJ" ),
( "Germany", "Norderney", "NRD" ),
( "Germany", "Nordholz-Speika", "NDZ" ),
( "Norfolk Island", "Norfolk Island", "NLK" ),
( "Russia", "Noril'sk", "NSK" ),
( "Australia", "Normanton, QL", "NTN" ),
( "Sweden", "Norrkoping", "NRK" ),
( "Vanuatu", "Norsup", "NUS" ),
( "Turks and Caicos Islands", "North Caicos", "NCA" ),
( "Bahamas", "North Eleuthera", "ELH" ),
( "United Kingdom", "North Ronaldsay", "NRL" ),
( "United Kingdom", "Norwich", "NWI" ),
( "Costa Rica", "Nosara Beach", "NOB" ),
( "Madagascar", "Nossi-be", "NOS" ),
( "United Kingdom", "Nottingham", "EMA" ),
( "Mauritania", "Nouadhiba", "NDB" ),
( "Mauritania", "Nouakchott", "NKC" ),
( "New Caledonia - Tontouta", "Noumea", "NOU" ),
( "New Caledonia - Magenta", "Noumea", "GEA" ),
( "Russia", "Novgorod", "NVR" ),
( "Russia", "Novokuznetsk", "NOZ" ),
( "Russia - Tolmachevo", "Novosibirsk", "OVB" ),
( "Cuba", "Nueva Gerona", "GER" ),
( "Mexico", "Nuevo Laredo", "NLD" ),
( "French Polynesia", "Nuku Hiva", "NHV" ),
( "Tonga", "Nuku'Alofa", "TBU" ),
( "Uzbekistan", "Nukus", "NCU" ),
( "Australia", "Numbulwar, NT", "NUB" ),
( "Indonesia", "Nunukan", "NNX" ),
( "Germany - Rail service", "Nuremberg", "ZAQ" ),
( "Germany", "Nuremberg", "NUE" ),
( "Greenland", "Nuuk", "GOH" ),
( "Sudan", "Nyala", "UYL" ),
( "Myanmar", "Nyaung", "NYU" ),
( "Australia", "Nyngan, NS", "NYN" ),
( "Mexico", "Oaxaca", "OAX" ),
( "Indonesia", "Obano", "OBD" ),
( "Japan", "Obihiro", "OBO" ),
( "Jamaica", "Ocho Rios", "OCJ" ),
( "Denmark", "Odense", "ZBQ" ),
( "Ukraine", "Odessa", "ODS" ),
( "Macedonia", "Ohrid", "OHD" ),
( "Japan", "Oita", "OIT" ),
( "Indonedia", "Okaba", "OKQ" ),
( "Japan", "Okayama", "OKJ" ),
( "Russia", "Okhotsk", "OHO" ),
( "Japan", "Okinawa", "OKA" ),
( "Japan", "Okoshiri", "OIR" ),
( "Indonesia", "Oksibil", "OKL" ),
( "Italy", "Olbia", "OLB" ),
( "Vanuatu", "Olpoi", "OLJ" ),
( "Australia", "Olympic Dam, SA", "OLP" ),
( "Gabon", "Omboue", "OMB" ),
( "Russia", "Omsk", "OMS" ),
( "Namibia", "Ondangwa", "OND" ),
( "Romania", "Oradea", "OMR" ),
( "Algeria", "Oran", "ORN" ),
( "Australia", "Orange, New South Wales", "OAG" ),
( "Namibia", "Oranjemund", "OMD" ),
( "Sweeden - Obrebro-Bofors", "Orebro", "ORB" ),
( "Russia", "Orenburg", "REN" ),
( "Pakistan", "Ormara", "ORW" ),
( "Sweden", "Ornskoldsvik", "OER" ),
( "Russia", "Orsk", "OSW" ),
( "Norway", "Orsta-Volda", "HOV" ),
( "Japan - all airports", "Osaka", "OSA" ),
( "Japan - Itami", "Osaka", "ITM" ),
( "Japan - Kansai Intl", "Osaka", "KIX" ),
( "Japan", "Oshima", "OIM" ),
( "Croatia", "Osijek", "OSI" ),
( "Sweden", "Oskarshamn", "OSK" ),
( "Norway", "Oslo", "OSL" ),
( "Norway - Sandefjord", "Torp Airport Oslo", "TRF" ),
( "Sweden", "Ostersund", "OSD" ),
( "Czech Republic", "Ostrava", "OSR" ),
( "Colombia", "Otu", "OTU" ),
( "Burkina Faso", "Ouagadougou", "OUA" ),
( "Algeria", "Ouargla", "OGX" ),
( "Morocco", "Ouarzazate", "OZZ" ),
( "Laos", "Oudomxay", "ODY" ),
( "Morocco", "Oujda", "OUD" ),
( "Finland", "Oulu", "OUL" ),
( "New Caledonia", "Ouvea", "UVE" ),
( "Israel", "Ovda", "VDA" ),
( "Gabon", "Oyem", "OYE" ),
( "Vanuatu", "Paama", "PBJ" ),
( "Greenland", "Paamiut", "JFR" ),
( "Indonesia", "Padang", "PDG" ),
( "Germany", "Paderborn", "PAD" ),
( "American Samoa", "Pago Pago", "PPG" ),
( "Laos", "Pakse", "PKZ" ),
( "Uganda", "Pakuba", "PAF" ),
( "Honduras", "Palacios", "PCH" ),
( "Indonesia", "Palang Karaya", "PKY" ),
( "Lithuania", "Palanga", "PLQ" ),
( "Indonesia", "Palembang", "PLM" ),
( "Mexico", "Palenque", "PQM" ),
( "Italy", "Palermo, Sicily", "PMO" ),
( "Spain and Canary Islands", "Palma Mallorca", "PMI" ),
( "Costa Rica", "Palmar", "PMZ" ),
( "Brazil", "Palmas, TO", "PMW" ),
( "New Zealand", "Palmerston North", "PMR" ),
( "Indonesia", "Palu", "PLW" ),
( "Spain", "Pamplona", "PNA" ),
( "Panama - Tocumen Intl", "Panama City", "PTY" ),
( "Panama - Paitilla", "Panama City", "PAC" ),
( "Indonesia", "Pangkalanboun", "PKN" ),
( "Indonesia", "Pangkalpinang", "PGK" ),
( "Pakistan", "Panjger", "PJG" ),
( "Italy", "Pantelleria", "PNL" ),
( "United Kingdom", "Papa Westray", "PPW" ),
( "French Polynesia", "Papeete", "PPT" ),
( "Cyprus", "Paphos", "PFO" ),
( "Pakistan", "Para Chinar", "PAJ" ),
( "Australia", "Paraburdoo, WA", "PBO" ),
( "Bahamas", "Paradise Island", "PID" ),
( "Suriname - Zanderij Intl", "Paramaribo", "PBM" ),
( "Suriname - Zorg En Hoop", "Paramaribo", "ORG" ),
( "Argentina", "Parana, ER", "PRA" ),
( "Solomon Islands", "Parasi", "PRS" ),
( "France - All airports", "Paris", "PAR" ),
( "France - Charles Degaulle", "Paris", "CDG" ),
( "France - Orly", "Paris", "ORY" ),
( "France - Beauvais-Tille", "Paris", "BVA" ),
( "Italy", "Parma/Milan", "PMF" ),
( "Brazil", "Parnaiba, PI", "PHB" ),
( "Bhutan", "Paro", "PBH" ),
( "Pakistan", "Pasni", "PSI" ),
( "Argentina", "Paso de Los Libres", "AOL" ),
( "Brazil", "Passo Fundo, RS", "PFB" ),
( "Colombia", "Pasto", "PSO" ),
( "India", "Patna", "PAT" ),
( "Greece", "Patras", "GPA" ),
( "France", "Pau", "PUF" ),
( "Kazakhstan", "Pavlodar", "PWQ" ),
( "Russia", "Pechora", "PEX" ),
( "Indonesia", "Pekanbaru", "PKU" ),
( "Brazil", "Pelotas, RS", "PET" ),
( "Mozambique", "Pemba", "POL" ),
( "Tanzania - Wawi", "Pemba", "PMA" ),
( "Malaysia", "Penang", "PEN" ),
( "Cook Islands", "Penrhyn Island", "PYE" ),
( "United Kingdom", "Penzance", "PZE" ),
( "Colombia", "Pereira", "PEI" ),
( "France", "Perigueux", "PGX" ),
( "Argentina", "Perito Moreno, SC", "PMQ" ),
( "Russia", "Perm", "PEE" ),
( "France", "Perpignan", "PGF" ),
( "Australia", "Perth, Western Australia", "PER" ),
( "Italy", "Perugia", "PEG" ),
( "Italy", "Pescara", "PSR" ),
( "Pakistan", "Peshawar", "PEW" ),
( "Brazil", "Petrolina, PE", "PNZ" ),
( "Russia", "Petropaulousk-Kamchats", "PKC" ),
( "Russia", "Petrozavodsk", "PES" ),
( "South Africa", "Phalaborwa", "PHW" ),
( "Thailand", "Phitsanulok", "PHS" ),
( "Cambodia", "Phnom Penh", "PNH" ),
( "Thailand", "Phrae", "PRH" ),
( "Viet Nam - Duong Dang", "Phu Quoc", "PQC" ),
( "Thailand", "Phuket", "HKT" ),
( "Portugal", "Pico Island", "PIX" ),
( "Mexico", "Piedras Negras", "PDS" ),
( "South Africa", "Pietermaritzburg", "PZB" ),
( "South Africa", "Pietersburb", "PTG" ),
( "Taiwan", "Pingtung", "PIF" ),
( "Italy - Gal Galilei", "Pisa", "PSA" ),
( "Greenland", "Pituffik", "THU" ),
( "Peru", "Piura", "PIU" ),
( "Belize", "Placencia", "PLJ" ),
( "Viet Nam", "Pleiku", "PXU" ),
( "South Africa", "Plettenburg Bay", "PBZ" ),
( "United Kingdom", "Plymouth", "PLH" ),
( "Serbia and Montenegro - Golubovci", "Podgoriea", "TGD" ),
( "Micronesia", "Pohnpei", "PNI" ),
( "Congo", "Pointe Noire", "PNR" ),
( "Guadeloupe", "Pointe-a-Pitre", "PTP" ),
( "France - Biard", "Poitiers", "PIS" ),
( "France - Rail service", "Poitiers", "XOP" ),
( "Nepal", "Pokhara", "PKR" ),
( "Ukraine", "Poltava", "PLV" ),
( "Russia", "Polyarnyj", "PYJ" ),
( "Puerto Rico", "Ponce", "PSE" ),
( "Portugal", "Ponta Delgada", "PDL" ),
( "Brazil", "Ponta Pora, MS", "PMG" ),
( "Indonesia", "Pontianak", "PNK" ),
( "Papua New Guinea", "Popondetta", "PNP" ),
( "Slovakia", "Popraol/Tatry", "TAT" ),
( "India", "Porbandar", "PBD" ),
( "Finland", "Pori", "POR" ),
( "Venezuela", "Porlamar", "PMV" ),
( "Jamaica", "Port Antonio", "POT" ),
( "Haiti", "Port Au Prince", "PAP" ),
( "Australia", "Port Augusta, SA", "PUG" ),
( "Madagascar", "Port Berge", "WPB" ),
( "India", "Port Blair", "IXZ" ),
( "South Africa", "Port Elizabeth", "PLZ" ),
( "Gabon", "Port Gentil", "POG" ),
( "Nigeria", "Port Harcourt", "PHC" ),
( "Australia", "Port Headland, WA", "PHE" ),
( "Australia", "Port Lincoln, SA", "PLO" ),
( "Australia", "Port Macquarie, NS", "PQQ" ),
( "Papua New Guinea", "Port Moresby", "POM" ),
( "Trinidad", "Port of Spain", "POS" ),
( "Falkland Islands", "Port Stanley", "PSY" ),
( "Sudan", "Port Sudan", "PZU" ),
( "Vanuatu", "Port Vila", "VLI" ),
( "Australia", "Portland, VI", "PTJ" ),
( "Brazil", "Porto Alegre, RS", "POA" ),
( "Portugal", "Porto Santo", "PXO" ),
( "Brazil", "Porto Seguro", "BPS" ),
( "Brazil", "Porto Velho, RO", "PVH" ),
( "Portugal", "Porto", "OPO" ),
( "Ecuador", "Portoviejo", "PVO" ),
( "Argentina", "Posadas, MI", "PSS" ),
( "Mexico", "Poza Rico", "PAZ" ),
( "Poland", "Poznan", "POZ" ),
( "Czech Republic", "Prague", "PRG" ),
( "Cape Verde", "Praia", "RAI" ),
( "Argentina", "Pres. Roque Saenz Pena, CH", "PRQ" ),
( "Brazil", "Presidente Prudente, SP", "PPB" ),
( "Greece", "Preveza/Lefkas", "PVK" ),
( "Serbia and Montenegro", "Pristina", "PRN" ),
( "Australia", "Proserpine, QL", "PPP" ),
( "Turks and Caicos Islands", "Providenciales", "PLS" ),
( "Peru", "Pucallpa", "PCL" ),
( "Mexico", "Puebla", "PBC" ),
( "Venezuela", "Puerto Ayacucha", "PYH" ),
( "Colombia", "Puerto Berria", "PBE" ),
( "Spain", "Puerto del Rosario", "FUE" ),
( "Argentina", "Puerto Deseado, SC", "PUD" ),
( "Mexico", "Puerto Escondido", "PXM" ),
( "Costa Rica", "Puerto Jimenez", "PJM" ),
( "Honduras", "Puerto Lempira", "PEU" ),
( "Argentina", "Puerto Madryn, CB", "PMY" ),
( "Peru", "Puerto Maldonado", "PEM" ),
( "Chile", "Puerto Montt", "PMC" ),
( "Venezuela", "Puerto Ordaz", "PZO" ),
( "Dominican Republic", "Puerto Plata", "POP" ),
( "Philippines", "Puerto Princesa", "PPS" ),
( "Bolivia", "Puerto Suarez", "PSZ" ),
( "Mexico", "Puerto Vallarta", "PVR" ),
( "Croatia", "Pula", "PUY" ),
( "India", "Pune", "PNQ" ),
( "Chile", "Punta Arenas", "PUQ" ),
( "Dominican Republic", "Punta Cana", "PUJ" ),
( "Uruguay", "Punta Del Este", "PDP" ),
( "Belize", "Punta Gorda", "PND" ),
( "Costa Rica", "Punta Islita", "PBP" ),
( "India", "Puttaparthi", "PUT" ),
( "Indonesia", "Putussibau", "PSU" ),
( "North Korea", "Pyongyang", "FNJ" ),
( "Saudi Arabia", "Qaisumah", "AQI" ),
( "Greenland", "Qaqortoq", "JJU" ),
( "China", "Qiemo", "IQM" ),
( "China", "Qingdao", "TAO" ),
( "China", "Qiqihar", "NDG" ),
( "New Zealand", "Queenstown", "ZQN" ),
( "Mozambique", "Quelimane", "UEL" ),
( "Costa Rica", "Quepos", "XQP" ),
( "Mexico", "Queretaro", "QRO" ),
( "Pakistan", "Quetta", "UET" ),
( "Viet Nam", "Qui Nhon", "UIH" ),
( "Colombia", "Quibdo", "UIB" ),
( "France", "Quimper", "UIP" ),
( "Australia", "Quipi, QL", "ULP" ),
( "Ecuador", "Quito", "UIO" ),
( "Papua New Guinea", "Rabaraba", "RBP" ),
( "Morocco", "Rabat", "RBA" ),
( "Papua New Guinea", "Rabaul", "RAB" ),
( "Viet Nam", "Rach Gia", "VKG" ),
( "Russia", "Raduzhnyi", "RAT" ),
( "Saudi Arabia", "Rafha", "RAH" ),
( "Iran", "Rafsanjan", "RJN" ),
( "French Polynesia", "Raiatea", "RFP" ),
( "India", "Rajkot", "RAJ" ),
( "Bangladesh", "Rajshahi", "RJH" ),
( "Solomon Islands", "Ramato", "RBV" ),
( "Australia", "Ramingining, NT", "RAM" ),
( "India", "Ranchi", "IXR" ),
( "Thailand", "Ranong", "UNN" ),
( "Cook Islands", "Rarotonga", "RAR" ),
( "United Arab Emirates", "Ras Al Khaimah", "RKT" ),
( "Iran", "Rasht", "RAS" ),
( "Cambodia", "Ratanakiri", "RBE" ),
( "Pakistan", "Rawala Kot", "RAZ" ),
( "Japan", "Rebun", "RBJ" ),
( "Brazil", "Recife, PE", "REC" ),
( "Argentina", "Reconquista, SF", "RCQ" ),
( "Italy", "Reggio Calabria", "REG" ),
( "Solomon Islands", "Rennell", "RNL" ),
( "France", "Rennes", "RNS" ),
( "Argentina", "Resistencia, CW", "RES" ),
( "Spain and Canary Islands", "Reus", "REU" ),
( "Iceland", "Reykjavik", "KEF" ),
( "Mexico", "Reynossa", "REX" ),
( "Gabon", "Rhodes", "RHO" ),
( "Brazil", "Ribeirao Preto, SP", "RAO" ),
( "Bolivia", "Riberalta", "RIB" ),
( "South Africa", "Richards Bay", "RCB" ),
( "Australia", "Richmond, QL", "RCM" ),
( "Latvia", "Riga", "RIX" ),
( "Croatia", "Rijeka", "RJK" ),
( "Italy", "Rimini", "RMI" ),
( "Brazil", "Rio Branco, AC", "RBR" ),
( "Argentina", "Rio Cuarto, CD", "RCU" ),
( "Brazil", "Rio De Janeiro, RJ", "GIG" ),
( "Argentina - Internacional", "Rio Gallegos", "RGL" ),
( "Brazil", "Rio Grande, RS", "RIG" ),
( "Argentina", "Rio Grande, TF", "RGA" ),
( "Argentina", "Rio Mayo, CB", "ROY" ),
( "Brazil", "Rio Verde, GO", "RVD" ),
( "Colombia", "Riohacha", "RCH" ),
( "Japan", "Rishiri", "RIS" ),
( "Saudi Arabia", "Riyadh", "RUH" ),
( "Yemen", "Riyan Mukalla", "RIY" ),
( "France", "Roane", "RNE" ),
( "Honduras", "Roatan", "RTB" ),
( "Viet Nam", "Roch Gia", "VKG" ),
( "Bahamas", "Rock Sound", "RSD" ),
( "Australia", "Rockhampton, QL", "ROK" ),
( "France", "Rodez", "RDZ" ),
( "Mauritius", "Rodrigues Island", "RRG" ),
( "Norway", "Roervik", "RVK" ),
( "Norway", "Rognan", "ZXM" ),
( "Australia", "Roma, QL", "RMA" ),
( "Italy - All airports", "Rome", "ROM" ),
( "Italy - Ciampino", "Rome", "CIA" ),
( "Italy - Leonardo Da Vinci/Fiumicino", "Rome", "FCO" ),
( "Marshall Islands", "Rongelap Island", "RNP" ),
( "Sweden", "Ronneby", "RNB" ),
( "Norway", "Roros", "RRS" ),
( "French Polynesia", "Rorutu", "RUR" ),
( "Argentina", "Rosario, SF", "ROS" ),
( "Iceland", "Rosh Pina", "RPN" ),
( "Norway", "Rost", "RET" ),
( "Germany", "Rostock-Laage", "RLG" ),
( "Russia", "Rostov", "ROV" ),
( "Northern Mariana Islands", "Rota", "ROP" ),
( "New Zealand", "Rotorua", "ROT" ),
( "Netherlands", "Rotterdam", "RTM" ),
( "France", "Rouen", "URO" ),
( "Finland", "Rovaniemi", "RVN" ),
( "Mexico", "S. Cristobal del Casas", "SZT" ),
( "Germany", "Saarbruecken", "QFZ" ),
( "U.S. Virgin Islands", "Saint Croix", "STX" ),
( "ST. LUCIA", "Saint Lucia", "SLU" ),
( "Netherlands Antilles", "Saint Maarten", "SXM" ),
( "Russia - Pulkovo", "Saint Petersburg", "LED" ),
( "U.S. Virgin Islands", "Saint Thomas", "STT" ),
( "France - La Mole", "Saint Tropez", "LTT" ),
( "France", "Saint Tropez", "XPZ" ),
( "Northern Mariana Islands", "Saipan", "SPN" ),
( "Thailand", "Sakon Nakhon", "SNO" ),
( "Russia", "Salehard", "SLY" ),
( "Turks and Caicos Islands", "Salt Cay", "SLX" ),
( "Mexico", "Saltillo", "SLW" ),
( "Brazil", "Salvadore, BA", "SSA" ),
( "Austria", "Salzburg", "SZG" ),
( "Russia", "Samara", "KUF" ),
( "Madagascar", "Sambaua", "SVB" ),
( "Kenya", "Samburu", "UAS" ),
( "Greece", "Samos", "SMI" ),
( "Colombia", "San Andres Island", "ADZ" ),
( "Argentina", "San Antonio Oesta, RN", "OES" ),
( "Venezuela", "San Antonio", "SVZ" ),
( "Argentina", "San Carlos", "BRC" ),
( "Costa Rica - Juan Santa Maria", "San Jose", "SJO" ),
( "Costa Rica - Tobias Bolanos Int'l", "San Jose", "SYQ" ),
( "Puerto Rico", "San Juan", "SJU" ),
( "Argentina", "San Juan, SJ", "UAQ" ),
( "Argentina", "San Julian, SC", "ULA" ),
( "Mexico", "San Luis Potosi", "SLP" ),
( "Argentina", "San Luis, SL", "LUQ" ),
( "San Marino", "San Marino", "SAI" ),
( "Argentina", "San Martin De Los Andes", "CPC" ),
( "Panama", "San Miguel", "NMG" ),
( "Honduras", "San Pedro Sula", "SAP" ),
( "Argentina", "San Rafael", "AFA" ),
( "Bahamas", "San Salvador", "ZSA" ),
( "El Salvador", "San Salvador", "SAL" ),
( "Spain", "San Sebastian", "EAS" ),
( "Yemen", "Sana'a", "SAH" ),
( "United Kingdom", "Sanday", "NDY" ),
( "Solomon Islands", "Santa Ana", "NNB" ),
( "Venezuela", "Santa Barbara, Ed", "STB" ),
( "Spain and Canary Islands - La Palma", "Santa Cruz De La Palma", "SPC" ),
( "Bolivia", "Santa Cruz", "VVI" ),
( "Brazil", "Santa Maria", "RIA" ),
( "Portugal", "Santa Maria", "SMA" ),
( "Colombia", "Santa Marta", "SMR" ),
( "Argentina", "Santa Rosa, LP", "RSA" ),
( "Brazil", "Santarem, PA", "STM" ),
( "Madagascar", "Sante Marie", "SMS" ),
( "Chile", "Santiago", "SCL" ),
( "Dominican Republic", "Santiago", "STI" ),
( "Brazil", "Santo Angelo", "GEL" ),
( "Cape Verde", "Santo Antao", "NTO" ),
( "Dominican Republic - Herrera", "Santo Domingo", "HEX" ),
( "Dominican Republic - Las Americas", "Santo Domingo", "SDQ" ),
( "Venezuela", "Santo Domingo", "STD" ),
( "China", "Sanya", "SYX" ),
( "Cape Verde", "Sao Nicolau", "SNE" ),
( "Brazil - Congonhas", "Sao Paulo", "CGH" ),
( "Brazil - Viracopos", "Sao Paulo", "VCP" ),
( "Brazil - Guarulhos Intl", "Sao Paulo", "GRU" ),
( "Sao Tome and Principe", "Sao Tome Is.", "TMS" ),
( "Cape Verde", "Sao Vicente", "VXE" ),
( "Japan - Chitose", "Sapporo", "CTS" ),
( "Japan - Okadama", "Sapporo", "OKD" ),
( "Vanuatu", "Sara", "SSR" ),
( "Russia", "Saratov", "RTW" ),
( "Indonesia", "Sarmi", "ZRM" ),
( "Romania", "Satu Mare", "SUJ" ),
( "Papua New Guinea", "Satwag", "SWG" ),
( "Brazil", "Sau Luiz, MA", "SLZ" ),
( "Indonesia", "Saumlaki", "SXK" ),
( "Laos", "Savannakhet", "ZVK" ),
( "Finland", "Savonlinna", "SVL" ),
( "Fiji", "Savusavu", "SVU" ),
( "Laos", "Sayaboury", "ZBY" ),
( "Solomon Islands", "Sege", "EGM" ),
( "Yemen", "Seiyun", "GXF" ),
( "Norway", "Selje", "QFK" ),
( "Indonesia", "Semarang", "SRG" ),
( "Indonesia", "Senggo", "ZEG" ),
( "South Korea - All Airports", "Seoul", "SEL" ),
( "South Korea - Gimpo International", "Seoul", "GMP" ),
( "South Korea - Incheon International", "Seoul", "ICN" ),
( "Indonesia", "Servi", "ZRI" ),
( "Namibia", "Sesriem", "SZM" ),
( "Spain and Canary Islands", "Sevilla", "SVQ" ),
( "China", "Shanghai", "PVG" ),
( "Ireland", "Shannon", "SNN" ),
( "China", "Shantou", "SWA" ),
( "Egypt", "Sharm El Sheikh", "SSH" ),
( "United Kingdom", "Sheffield", "SZD" ),
( "China", "Shenzhen", "SZX" ),
( "United Kingdom - Lerwick/Tingwall", "Shetland Islands", "LWK" ),
( "United Kingdom - Sumburgh", "Shetland Islands", "LSI" ),
( "Ethiopia", "Shillavo", "HIL" ),
( "Kazakhstan", "Shimkent", "CIT" ),
( "Iran", "Shiraz", "SYZ" ),
( "Japan", "Shonai", "SYO" ),
( "Australia", "Shute Harbor", "JHQ" ),
( "Cambodia", "Siem Reap", "REP" ),
( "India", "Silchar", "IXS" ),
( "China", "Simao", "SYM" ),
( "Indonesia", "Sinak", "NKD" ),
( "Singapore - Changi", "Singapore", "SIN" ),
( "Singapore - Seletar", "Singapore", "XSP" ),
( "Indonesia", "Sintang", "SQG" ),
( "Greenland", "Sisimiut", "JHS" ),
( "Myanmar", "Sittwe", "AKY" ),
( "Turkey", "Sivas", "VAS" ),
( "Greece", "Skiathos", "JSI" ),
( "Macedonia (FYROM)", "Skopie", "SKP" ),
( "Sweden", "Skovde", "KVB" ),
( "South Africa", "Skukuza", "SZK" ),
( "Ireland", "Sligo", "SXL" ),
( "Madagascar", "Soalala", "DWB" ),
( "Sweden", "Soderham", "SOO" ),
( "Bulgaria", "Sofia", "SOF" ),
( "Norway", "Sognolal", "SOG" ),
( "Indonesia", "Solo City", "SOC" ),
( "Viet Nam - Na-San", "Son-La", "SQH" ),
( "Norway", "Sorkjosen", "SOJ" ),
( "Brazil", "Sorocaba", "SOD" ),
( "Bahamas", "South Andros", "TZN" ),
( "Turks and Caicos Islands", "South Caicos", "XSC" ),
( "United Kingdom", "South Hampton", "SOU" ),
( "Australia", "South Molle Island, QL", "SOI" ),
( "Croatia", "Split", "SPU" ),
( "Bahamas", "Spring Point", "AXP" ),
( "India", "Srinagar", "SXR" ),
( "U.S. Virgin Islands", "St. Croix Island", "STX" ),
( "Reunion", "St Denis de la Reunion", "RUN" ),
( "St Kitts and Nevis", "St Kitts", "SKB" ),
( "St Pierre and Miquelon", "St Pierre", "FSP" ),
( "Saint Vincent and the Grenadines", "St Vincent", "SVD" ),
( "France", "St. Etienne", "EBU" ),
( "Netherlands Antilles", "St. Eustatius", "EUX" ),
( "St. Lucia - Hawnorra", "St. Lucia", "UVF" ),
( "St. Lucia", "St. Lucia", "UVF" ),
( "Russia", "St. Petersburg", "LED" ),
( "Reunion", "St. Pierre de la Reunion", "ZSE" ),
( "U.S. Virgin Islands", "St. Thomas Island", "STT" ),
( "Russia", "Stavropol", "STW" ),
( "Norway", "Stavanger", "SVG" ),
( "Bahamas", "Stella Maris", "SML" ),
( "Sweden - All airports", "Stockholm", "STO" ),
( "Sweden - Arlanda", "Stockholm", "ARN" ),
( "Sweden - Bromma", "Stockholm", "BMA" ),
( "United Kingdom", "Stornoway", "SYY" ),
( "Sweden", "Storuman", "SQO" ),
( "France - Bus service", "Strasbourg", "XER" ),
( "France - Entzheim", "Strasbourg", "SXB" ),
( "United Kingdom", "Stronsay", "SOY" ),
( "Cambodia", "Stung Treng", "TNX" ),
( "Germany - Echterdingen", "Stuttgart", "STR" ),
( "Germany - Rail service", "Stuttgart", "ZWS" ),
( "Solomon Islands", "Suavanao", "VAO" ),
( "Bolivia", "Sucre", "SRE" ),
( "Australia", "Sue Island, QL", "SYU" ),
( "Pakistan", "Sui", "SUL" ),
( "Thailand", "Sukhotthai", "THS" ),
( "South Africa", "Sun City", "NTY" ),
( "Australia", "Sunshine Coast, QL", "MCY" ),
( "Indonesia", "Surabaya", "SUB" ),
( "Thailand", "Surat Thani", "URT" ),
( "Fiji", "Suva", "SUV" ),
( "Sweden", "Sveg", "EVG" ),
( "Norway", "Svolvaer", "SVJ" ),
( "Australia", "Sydney, New South Wales", "SYD" ),
( "Bangladesh", "Sylhet", "ZYL" ),
( "Poland", "Szczecin", "SZZ" ),
( "Egypt", "Taba", "TCP" ),
( "Tunisia", "Tabarka", "TBJ" ),
( "Brazil", "Tabatinga, AM", "TBT" ),
( "Tanzania", "Tabora", "TBO" ),
( "Iran", "Tabriz", "TBZ" ),
( "Papua New Guinea", "Tabubil", "TBG" ),
( "Saudi Arabia", "Tabuk", "TUU" ),
( "China", "Tacheng", "TCG" ),
( "Myanmar", "Tachilek", "THL" ),
( "Philippines", "Tacloban", "TAC" ),
( "Peru", "Tacna", "TCQ" ),
( "Taiwan", "Taichung", "TXG" ),
( "Saudi Arabia", "Taif", "TIF" ),
( "Taiwan", "Tainan", "TNN" ),
( "Taiwan - Sung Shan", "Taipei", "TSA" ),
( "Taiwan - Chiang Kai Shek", "Taipei", "TPE" ),
( "Taiwan", "Taitung", "TTT" ),
( "China", "Taiyuan", "TYN" ),
( "Yemen", "Taiz", "TAI" ),
( "Estonia", "Tallinn", "TLL" ),
( "Algeria", "Tamanrasset", "TMR" ),
( "Costa Rica", "Tamarindo", "TNO" ),
( "Madagascar", "Tamatave", "TMM" ),
( "Madagascar", "Tambohorano", "WTA" ),
( "Indonesia", "Tambolaka", "TMC" ),
( "Costa Rica", "Tambor", "TMU" ),
( "Finland", "Tampere", "TMP" ),
( "Mexico", "Tampico", "TAM" ),
( "Australia", "Tamworth, NS", "TMW" ),
( "Indonesia", "Tanahmerah", "TMH" ),
( "Morocco", "Tangier", "TNG" ),
( "Indonesia", "Tanjung Pandan", "TJQ" ),
( "Indonesia", "Tanjung Selor", "TJS" ),
( "Vanuatu", "Tanna", "TAH" ),
( "Mexico", "Tapachula", "TAP" ),
( "Indonesia", "Tarakan", "TRK" ),
( "Japan", "Taramajma", "TRA" ),
( "Italy", "Taranto", "TAR" ),
( "Peru", "Tarapoto", "TPP" ),
( "Kiribati", "Tarawa", "TRW" ),
( "Australia", "Taree, NS", "TRO" ),
( "Papua New Guinea", "Tari", "TIZ" ),
( "Bolivia", "Tarija", "TJA" ),
( "Uzbekistan", "Tashkent", "TAS" ),
( "New Zealand", "Taupo", "TUO" ),
( "New Zealand", "Tauranga", "TRG" ),
( "Fiji", "Taveuni", "TVU" ),
( "Malaysia", "Tawau", "TWU" ),
( "Algeria", "Tbessa", "TEE" ),
( "Georgia", "Tbilisi", "TBS" ),
( "Gabon", "Tchibanga", "TCH" ),
( "New Zealand", "Te Anau", "TEU" ),
( "United Kingdom", "Teesside", "MME" ),
( "Brazil", "Tefe, AM", "TFF" ),
( "Honduras", "Tegucigalpa", "TGU" ),
( "Iran - Mehrabad", "Tehran", "THR" ),
( "Papua New Guinea", "Tekadu", "TKB" ),
( "Israel", "Tel Aviv", "TLV" ),
( "Indonesia", "Tembagapura", "TIM" ),
( "Indonesia", "Teminabuan", "TXM" ),
( "Chile", "Temuco", "ZCO" ),
( "Spain and Canary Islands - Norte Los Rodeos", "Tenerife", "TFN" ),
( "Spain and Canary Islands - Sur Reina Sofia", "Tenerife", "TFS" ),
( "Australia", "Tennant Creek, NT", "TCA" ),
( "Mexico", "Tepic", "TPQ" ),
( "Portugal", "Terceira Island", "TER" ),
( "Brazil", "Teresina, PI", "THE" ),
( "Uzbekistan", "Termez", "TMJ" ),
( "Indonesia", "Ternate", "TTE" ),
( "Papua New Guinea", "Tetabedi", "TDB" ),
( "Mozambique", "Tete", "TET" ),
( "Morocco", "Tetuan", "TTU" ),
( "India", "Tezpur", "TEZ" ),
( "Myanmar", "Thandwe", "SNW" ),
( "Australia", "Thangool, QL", "THG" ),
( "Australia", "Thargomindah, QL", "XTG" ),
( "Bahamas", "The Bight", "TBI" ),
( "Greece", "Thessaloniki", "SKG" ),
( "Greece", "Thira", "JTR" ),
( "India", "Thiruvananthapuram", "TRV" ),
( "Iceland", "Thorshofn", "THO" ),
( "Australia", "Thursday Island, QL", "TIS" ),
( "China", "Tianjn", "TSN" ),
( "Algeria", "Tiaret", "TID" ),
( "New Caledonia", "Tiga", "TGJ" ),
( "Mexico", "Tijuana", "TIJ" ),
( "French Polynesia", "Tikehau Atoll", "TIH" ),
( "Russia", "Tiksi", "IKS" ),
( "New Zealand", "Timaru", "TIU" ),
( "Algeria", "Timimoun", "TMX" ),
( "Romania", "Timosoara", "TSR" ),
( "Algeria", "Tindouf", "TIN" ),
( "Northern Mariana Islands", "Tinian", "TIQ" ),
( "Mauritania", "Tioljikja", "TIY" ),
( "Malaysia", "Tioman", "TOD" ),
( "Ethiopia", "Tippi", "TIE" ),
( "Albania", "Tirana", "TIA" ),
( "United Kingdom", "Tiree", "TRE" ),
( "Romania", "Tirgu Mures", "TGM" ),
( "India", "Tiruchirapally", "TRZ" ),
( "India", "Tirupati", "TIR" ),
( "Serbia and Montenegro", "Tivat", "TIV" ),
( "Algeria", "Tlemcen", "TLM" ),
( "Trinidad and Tobago", "Tobago", "TAB" ),
( "Libya", "Tobruk", "TOB" ),
( "Japan", "Tokunoshima", "TKN" ),
( "Japan", "Tokushima", "TKS" ),
( "Japan - All airports", "Tokyo", "TYO" ),
( "Japan - Haneda", "Tokyo", "HND" ),
( "Japan - Narita", "Tokyo", "NRT" ),
( "Brazil", "Toledo, PR", "TOW" ),
( "Mexico", "Toluco", "TLC" ),
( "Australia", "Tom Price, WA", "TPR" ),
( "Malaysia", "Tomanggong", "TMG" ),
( "Mali", "Tombouctou", "TOM" ),
( "Russia", "Tomsk", "TOF" ),
( "China", "Tongliao", "TGO" ),
( "Vanuatu", "Tongoa", "TGH" ),
( "Australia", "Toowoomba, QL", "TWB" ),
( "Mexico", "Torreon", "TRC" ),
( "Vanuatu", "Torres", "TOH" ),
( "Sweden", "Torsby", "TYF" ),
( "British Virgin Islands", "Tortola", "TOV" ),
( "Italy", "Tortoli", "TTB" ),
( "Costa Rica", "Tortuquero", "TTQ" ),
( "Japan", "Tottori", "TTJ" ),
( "New Caledonia", "Touho", "TOU" ),
( "France", "Toulon", "TLN" ),
( "France", "Toulouse", "TLS" ),
( "France", "Tours", "TUF" ),
( "France - Rail service", "Tours", "XSH" ),
( "Australia", "Townsville, QL", "TSV" ),
( "Japan", "Toyama", "TOY" ),
( "Tunisia", "Tozeur", "TOE" ),
( "Turkey", "Trabzon", "TZX" ),
( "Thailand", "Trang", "TST" ),
( "Italy", "Trapani", "TPS" ),
( "Australia", "Traralgon, VI", "TGN" ),
( "Bahamas", "Treasure Cay", "TCB" ),
( "Argentina", "Trelew, CB", "REL" ),
( "Italy", "Trieste", "TRS" ),
( "Bolivia", "Trinidad", "TDD" ),
( "Trinidad and Tobago", "Trinidad", "POS" ),
( "Libya", "Tripoli", "TIP" ),
( "Sweden", "Trollhattan", "THN" ),
( "Brazil", "Trombetas, PA", "TMT" ),
( "Norway", "Tromso", "TOS" ),
( "Norway", "Trondheim", "TRD" ),
( "Honduras", "Trujillo", "TJI" ),
( "Peru", "Trujillo", "TRU" ),
( "Micronesia", "Truk", "TKK" ),
( "Madagascar", "Tsaratanana", "TTS" ),
( "Madagascar", "Tsiroanomandidy", "WTS" ),
( "Namibia", "Tsumeb", "TSB" ),
( "Japan", "Tsushima", "TSJ" ),
( "French Polynesia", "Tubuai", "TUB" ),
( "Argentina", "Tucuman, TU", "TUC" ),
( "Venezuela", "Tucupita", "TUV" ),
( "Brazil", "Tucurui, PA", "TUR" ),
( "Papua New Guinea", "Tufi", "TFI" ),
( "Philippines", "Tuguegarao", "TUG" ),
( "Ecuador", "Tulcan", "TUA" ),
( "Madagascar", "Tulear", "TLE" ),
( "Ethiopia", "Tum", "TUJ" ),
( "Colombia", "Tumaco", "TCO" ),
( "Peru", "Tumbes", "TBP" ),
( "Tunisia", "Tunis", "TUN" ),
( "China", "Tunxi", "TXN" ),
( "Saudi Arabia", "Turaif", "TUI" ),
( "Pakistan", "Turbat", "TUK" ),
( "Italy", "Turin", "TRN" ),
( "Finland", "Turku", "TKU" ),
( "Mexico", "Tuxtla Gutierrez", "TGZ" ),
( "Russia", "Tyumen", "TJM" ),
( "Japan", "Ube", "UBJ" ),
( "Brazil", "Uberaba, MG", "UBA" ),
( "Brazil", "Uberlandia, MG", "UDI" ),
( "Thailand", "Ubon Ratchathani", "UBP" ),
( "India", "Udaipur", "UDR" ),
( "Thailand", "Udon Thani", "UTH" ),
( "Russia", "Ufa", "UFA" ),
( "Marshall Islands", "Ujae Island", "UJE" ),
( "Indonesia", "Ujung Pandang", "UPG" ),
( "Russia", "Ukhta", "UCT" ),
( "Mongolia", "Ulaanbaatar", "ULN" ),
( "China", "Ulanhot", "HLH" ),
( "Russia", "Ulan-Ude", "UUD" ),
( "Vanuatu", "Ulei", "ULB" ),
( "Mongolia", "Uliastai", "ULY" ),
( "Micronesia", "Ulithi", "ULI" ),
( "South Korea", "Ulsan", "USN" ),
( "South Africa", "Ulundi", "ULD" ),
( "Sweden", "Umea", "UME" ),
( "South Africa", "Umtata", "UTT" ),
( "Greenland", "Upernavik", "JUV" ),
( "South Africa", "Upington", "UTN" ),
( "Russia", "Uraj", "URJ" ),
( "Kazakhstan", "Uralsk", "URA" ),
( "Uzbekistan", "Urgench", "UGC" ),
( "Iran", "Urmieh", "OMH" ),
( "Papua New Guinea", "Uroubi", "URU" ),
( "Mexico", "Uruapan", "UPN" ),
( "Brazil", "Uruguaiana, RS", "URG" ),
( "China", "Urumqi", "URC" ),
( "Australia", "Useless Loop, WA", "USL" ),
( "Argentina", "Ushuaia, TF", "USH" ),
( "Russia", "Usinsk", "USK" ),
( "Kazakhstan", "Ust-Kamenogorsk", "UKK" ),
( "Russia", "Ust-Ilimsk", "UIK" ),
( "Thailand", "Utapao", "UTP" ),
( "Honduras", "Utila", "UII" ),
( "Marshall Islands", "Utirik Island", "UTK" ),
( "Greeland", "Uummannaq", "UMD" ),
( "Ukraine", "Uzhgorod", "UDJ" ),
( "Finland", "Vaasa", "VAA" ),
( "India", "Vadodara", "BDQ" ),
( "Norway", "Vadso", "VDS" ),
( "Chile", "Valdivia", "ZAL" ),
( "Spain", "Valencia", "VLC" ),
( "Venezuela", "Valencia", "VLN" ),
( "France", "Valenciennes", "XVS" ),
( "Venezuela", "Valera", "VLV" ),
( "Vanuatu", "Valesdir", "VLS" ),
( "Spain and Canary Islands", "Valladolid", "VLL" ),
( "Colombia", "Valledupar", "VUP" ),
( "Spain and Canary Islands - Hierro", "Valverde", "VDE" ),
( "Turkey", "Van", "VAN" ),
( "BC", "Vancouver", "YVR" ),
( "Papua New Guinea", "Vanimo", "VAI" ),
( "Fiji", "Vanuabalavu", "VBV" ),
( "India", "Varanasi", "VNS" ),
( "Norway", "Vardoe", "VAW" ),
( "Brazil", "Varginha, MG", "VAG" ),
( "Finland", "Varkaus", "VRK" ),
( "Bulgaria", "Varna", "VAR" ),
( "Sweden", "Vasteras", "VST" ),
( "Madagascar", "Vatomatry", "VAT" ),
( "Tonga", "Vava'u", "VAV" ),
( "Sweden", "Vaxjo", "VXO" ),
( "Antigua & Barbuda", "V.C. Bird International", "ANU" ),
( "Italy - Marco Polo", "Venice", "VCE" ),
( "Italy - Treviso", "Venice", "TSF" ),
( "Mexico", "Veracruz", "VER" ),
( "Cuba", "Varadero", "VRA" ),
( "Italy", "Verona", "VRN" ),
( "Iceland", "Vestmannaeyjar", "VEY" ),
( "Zimbabwe", "Victoria Falls", "VFA" ),
( "Australia", "Victoria River Downs, NT", "VCD" ),
( "Argentina", "Viedma, RN", "VDM" ),
( "Austria", "Vienna", "VIE" ),
( "Laos - Wattay", "Vientiane", "VTE" ),
( "Puerto Rico", "Vieques", "VQS" ),
( "Spain", "Vigo", "VGO" ),
( "Mozambique", "Vilanculos", "VNX" ),
( "Sweden", "Vilhelmina", "VHM" ),
( "Brazil", "Vilhena", "BVH" ),
( "Argentina", "Villa Gesell, BA", "VLG" ),
( "Argentina", "Villa Mercedes, SL", "VME" ),
( "Mexico", "Villahermosa", "VSA" ),
( "Lithuania", "Vilnius", "VNO" ),
( "Viet Nam", "Vinh City", "VII" ),
( "British Virgin Islands", "Virgin Gorda", "VIJ" ),
( "Sweden", "Visby", "VBY" ),
( "India", "Vishakhapatnam", "VTZ" ),
( "Belarus", "Vitebsk", "VTB" ),
( "Brazil", "Vitoria da Conquista, BA", "VDC" ),
( "Spain and Canary Islands", "Vitoria", "VIT" ),
( "Papua New Guinea", "Vivigani", "VIV" ),
( "Russia", "Vladikavkaz", "OGZ" ),
( "Russia", "Vladivostok", "VVO" ),
( "Madagascar", "Vohemar", "VOH" ),
( "Russia", "Volgodonsk", "VLK" ),
( "Russia", "Volgograd", "VOG" ),
( "Iceland", "Vopnafjordur", "VPN" ),
( "Russia", "Vorkuta", "VKT" ),
( "Russia", "Voronezh", "VOZ" ),
( "Saudi Arabia", "Wadi Ad Dawasir", "WAE" ),
( "Sudan", "Wadi Halfa", "WHF" ),
( "Indonesia", "Wagethe", "WET" ),
( "Australia", "Wagga Wagga, NS", "WGA" ),
( "Indonesia", "Wahai", "WBA" ),
( "Indonesia", "Waingapo", "WGP" ),
( "Japan", "Wakkanai", "WKJ" ),
( "Vanuatu", "Walaha", "WLH" ),
( "Australia", "Walgett, NS", "WGE" ),
( "Wallis and Futuna Islands", "Wallis Island", "WLS" ),
( "Namibia", "Walvis Bay", "WVB" ),
( "Indonesia", "Wamena", "WMX" ),
( "New Zealand", "Wanaka", "WKA" ),
( "New Zealand", "Wanganui", "WAG" ),
( "Germany", "Wangerooge", "AGE" ),
( "Papua New Guinea", "Wanigela", "AGL" ),
( "China", "Wanxian", "WXN" ),
( "Poland", "Warsaw", "WAW" ),
( "Indonesia", "Wasior", "WSR" ),
( "Papua New Guinea", "Wasu", "WSU" ),
( "Ireland", "Waterford", "WAT" ),
( "Papua New Guinea", "Wau", "WUG" ),
( "Sudan", "Wau", "WUU" ),
( "Papua New Guinea", "Wedau", "WED" ),
( "Saudi Arabia", "Wedjh", "EJH" ),
( "China", "Weihai", "WEH" ),
( "Australia", "Weipa, QL", "WEI" ),
( "New Zealand", "Wellington", "WLG" ),
( "China", "Wenzhou", "WNZ" ),
( "Germany", "Westerland", "GWT" ),
( "New Zealand", "Westport", "WSZ" ),
( "United Kingdom", "Westray", "WRY" ),
( "Papua New Guinea", "Wewak", "WWK" ),
( "New Zealand", "Whakatane", "WHK" ),
( "New Zealand", "Whangarei", "WRE" ),
( "Australia", "Whyalla, SA", "WYA" ),
( "United Kingdom", "Wick", "WIC" ),
( "Germany", "Wilhelmshaven", "WVN" ),
( "Australia", "Wiluna, WA", "WUN" ),
( "Australia", "Windarra, QL", "WNR" ),
( "Australia", "Winton, QL", "WIN" ),
( "Marshall Islands", "Woja", "WJA" ),
( "Taiwan", "Wonan", "WOT" ),
( "South Korea", "WonJu", "WJU" ),
( "Marshall Islands", "Wotho Island", "WTO" ),
( "Marshall Islands", "Wotje Island", "WTE" ),
( "Poland", "Wroclaw", "WRO" ),
( "Australia", "Wudinna, SA", "WUD" ),
( "China", "Wuhan", "WUH" ),
( "China", "Wuyishan", "WUS" ),
( "Australia", "Wyndham, WA", "WYN" ),
( "China", "Xiamen", "XMN" ),
( "China - Xianyang", "Xi An", "XIY" ),
( "China", "Xiangfan", "XFN" ),
( "China", "Xichang", "XIC" ),
( "Laos", "Xieng Khouang", "XKH" ),
( "China", "Xilinhot", "XIL" ),
( "China", "Xining", "XNN" ),
( "China", "Xuzhou", "XUZ" ),
( "Russia", "Yakutsk", "YKS" ),
( "Papua New Guinea", "Yalumet", "KYX" ),
( "Australia", "Yam Island, QL", "XMY" ),
( "Japan", "Yamagata", "GAJ" ),
( "China", "Yan'an", "ENY" ),
( "Saudi Arabia", "Yanbu", "YNB" ),
( "China", "Yancheng", "YNZ" ),
( "Solomon Islands", "Yandina", "XYA" ),
( "Myanmar", "Yangon", "RGN" ),
( "China", "Yanji", "YNJ" ),
( "China", "Yantai", "YNT" ),
( "Cameroon", "Yaounde", "YAO" ),
( "Micronesia", "Yap", "YAP" ),
( "Russia", "Yaroslavl", "IAR" ),
( "Iran", "Yazd", "AZD" ),
( "Mali", "Yelimane", "EYL" ),
( "South Korea", "Yeosu", "RSU" ),
( "Armenia", "Yerevan", "EVN" ),
( "China", "Yibin", "YBP" ),
( "China", "Yichang", "YIH" ),
( "China", "Yinchuan", "INC" ),
( "China", "Yining", "YIN" ),
( "China", "Yiwu", "YIW" ),
( "Indonesia", "Yogyakarta", "JOG" ),
( "Japan", "Yonago", "YGJ" ),
( "Japan", "Yonaguni Jima", "OGN" ),
( "Australia", "Yorke Island, QL", "OKR" ),
( "Japan", "Yoronjima", "RNJ" ),
( "China", "Yulin", "UYN" ),
( "Russia", "Yuzhno-Sakhalinsk", "UUS" ),
( "Croatia", "Zadar", "ZAD" ),
( "Croatia", "Zagreb", "ZAG" ),
( "Iran", "Zahedan", "ZAH" ),
( "Greece", "Zakinthos Island", "ZTH" ),
( "Philippines", "Zamboanga", "ZAM" ),
( "Tanzania - Kisauni", "Zanzibar", "ZNZ" ),
( "Ukraine", "Zaporozhye", "OZH" ),
( "Spain and Canary Islands", "Zaragoza", "ZAZ" ),
( "China", "Zhanjiang", "ZHA" ),
( "China", "Zhaotong", "ZAT" ),
( "China", "Zhengzha", "CGO" ),
( "Pakistan", "Zhob", "PZH" ),
( "China", "Zhoushan", "HSN" ),
( "China", "Zhuhai", "ZUH" ),
( "Poland", "Zielana Góra", "IEG" ),
( "Mexico", "Zihuatanejo/Ixtapa", "ZIH" ),
( "Mauritania", "Zouerate", "OUZ" ),
( "Indonesia", "Zugapa", "UGU" ),
( "Switzerland", "Zurich", "ZRH" ),
]